### ISSUE TITLE
Feathers throwing unexpected error

### ISSUE THREAD

**Issue by JeremiTraverse** [feathersjs/feathers#1019]
### Steps to reproduce
When I try to generate a service or an app, I get this weird error.

/usr/local/lib/node_modules/@feathersjs/cli/lib/index.js:6
const { upgrade } = require('@feathersjs/tools');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/@feathersjs/cli/bin/feathers.js:5:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)

### Expected behavior
Generating an app/service

### System configuration
**feathers cli version: @feathersjs/cli@3.8.4**
**Node version: 5.0.0**
**OS : Ubuntu 18.04**

**Comment by daffl** [comment]
Feathers requires [Node version 6 or later](https://docs.feathersjs.com/guides/basics/setup.html), you are using version 5.
