### ISSUE TITLE
Error passed to winston includes hook

### ISSUE THREAD

**Issue by dottodot** [feathersjs/feathers#1220]
I'm not sure if this is expected behaviour or not but if i throw a error in a hook like

```
  if (!result) {
    const error = new errors.NotAcceptable(
      'Code not found, please check and try again.'
    );
    console.log(error);
    throw error;
  }
```
logs an error as
```
{ NotAcceptable: Code not found, please check and try again.
    at new NotAcceptable (/node_modules/@feathersjs/errors/lib/index.js:128:17)
    at Object.module.exports (/src/hooks/apply-discount.js:15:19)
    at promise.then.hookObject (/node_modules/@feathersjs/commons/lib/hooks.js:142:73)
  type: 'FeathersError',
  name: 'NotAcceptable',
  message: 'Code not found, please check and try again.',
  code: 406,
  className: 'not-acceptable',
  data: undefined,
  errors: {} }
```
but the error that's received in my winston transport is the same but with the complete hook object attached to it i.e  (that's not the complete error as the hook contains app, params, data etc)
```
{ NotAcceptable: Code not found, please check and try again.
    at new NotAcceptable (/node_modules/@feathersjs/errors/lib/index.js:128:17)
    at Object.module.exports (/src/hooks/apply-discount.js:15:19)
    at promise.then.hookObject (/node_modules/@feathersjs/commons/lib/hooks.js:142:73)
  type: 'FeathersError',
  name: 'NotAcceptable',
  message: 'Code not found, please check and try again.',
  code: 406,
  className: 'not-acceptable',
  data: undefined,
  errors: {},
hook:
   { type: 'after',
     arguments: [ [Object], [Object] ],
     service:
      { options: [Object],
        create: [Function: newMethod],
        methods: [Object],
        hooks: [Function: hooks],
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        setMaxListeners: [Function: setMaxListeners],
        getMaxListeners: [Function: getMaxListeners],
        emit: [Function: emit],
        addListener: [Function: addListener],
        on: [Function: addListener],
        prependListener: [Function: prependListener],
        once: [Function: once],
        prependOnceListener: [Function: prependOnceListener],
        removeListener: [Function: removeListener],
        off: [Function: removeListener],
        removeAllListeners: [Function: removeAllListeners],
        listeners: [Function: listeners],
        rawListeners: [Function: rawListeners],
        listenerCount: [Function: listenerCount],
        eventNames: [Function: eventNames],
        publish: [Function: publish],
        _emit: [Function],
        app: [EventEmitter],
        _super: undefined,
        [Symbol(@feathersjs/transport-commons/publishers)]: {} }
}}
```

**Comment by dottodot** [comment]
Found it. In my logger hook I had

```
    logger.error(context.error);
```
rather than
```
    logger.error(context.error.stack);
```
