### ISSUE TITLE
How extends app to custom hooks?

### ISSUE THREAD

**Issue by matiaslopezd** [feathersjs/feathers#1233]
I try create a custom hook for validate JWT in all request of services , but I can't because need find data. I try make this:

`myservice.hooks.js`
```js
const authentication = require('@feathersjs/authentication');
const validateJWT = require('../../hooks/validate-token') //My custom hooks

module.exports = {
  before: {
    all: [authentication.hooks.authenticate('jwt'), validateJWT()],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },
}
```
`validate-token.js`
```js
const errors = require('@feathersjs/errors');
const feathers = require('@feathersjs/feathers');

module.exports = function (options = {}) {
 return async context => {

      const app = feathers();
      const jwt = app.service('jwt');
      const token = context.params.headers.authorization;
      //Check with the context header Authorization validation JWT token
      const valid = await jwt.find({
        token: token
      });
      // Return context with valid token or block request
      if(valid.data.length > 0){
        return context;
      }
      else{
        return new errors.NotAuthenticated('Invalid token').toJSON();
      }
  };  
}:
```
`log`

```console
error: TypeError: Cannot read property 'find' of undefined
    at Object.<anonymous> (C:\xampp\htdocs\api-feathers\src\hooks\validate-token.js:15:31)
    at promise.then.hookObject (C:\xampp\htdocs\api-feathers\node_modules\@feathersjs\commons\lib\hooks.js:142:73)
```

**Comment by daffl** [comment]
You are creating a new Feathers application where you probably want to use [context.app](https://docs.feathersjs.com/api/hooks.html#contextapp):

```js
module.exports = function (options = {}) {
 return async context => {
      const { app } = context;
      const jwt = app.service('jwt');
      const token = context.params.headers.authorization;
      //Check with the context header Authorization validation JWT token
      const valid = await jwt.find({
        token: token
      });
      // Return context with valid token or block request
      if(valid.data.length > 0){
        return context;
      }
      else{
        return new errors.NotAuthenticated('Invalid token').toJSON();
      }
  };  
}
```

**Comment by matiaslopezd** [comment]
@daffl really thanks!
