### ISSUE TITLE
Errors result in GeneralError without specifics of the cause

### ISSUE THREAD

**Issue by nidkil** [feathersjs/feathers#1274]
### Steps to reproduce

I might be doing something wrong, but in a lot of cases when errors are thrown and converted to a Feathers GeneralError the details of the actual error that was thrown are missing. This is very frustrating when it is an error in say production, as you have no clue what is causing the error.

What I have noticed in my own code: when an error is thrown without the `new` keyword (throw Error versus throw new Error) the Feathers GeneralError does not contain the error details. So in my own code I have changed this everywhere to use the `new` keyword. However I do not have control over external modules I am using.

### Expected behavior
I would expect errors to be caught by Feathers, converted to a General Error and for the original error details to be added to it.

### Actual behavior
The error is caught and converted to a Feathers GeneralError but without the original error details.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): 

@feathersjs/feathers: 3.1.7
@feathersjs/errors: 3.3.0

**NodeJS version**: 10.9.0

**Operating System**: Windows 10 and Linuix 18.1

**Browser Version**: n/a

**React Native Version**: n/a

**Module Loader**: n/a

**Comment by KidkArolis** [comment]
Looks to me like the original message and stack should be preserved: https://github.com/feathersjs/feathers/blob/33337790d988d4a996df3318a9c09f95e95b1080/packages/errors/lib/error-handler.js#L33-L39 when you're using this default error-handler.

Which error details are you missing?

**Comment by nidkil** [comment]
Hi,

I get the plain vanilla GeneralError without any other details. You can try and recreate it by throwing an error with out the `new` keyword, e.g.

```
throw Error('Where is my error message and error stack?');
```

Should do the trick.

**Comment by nidkil** [comment]
Another example of the actual error not being passed on with GeneralError is when a call is done on an object property of which the parent does not exist. For example:

```
const initialized = {
  parent: {
    child: true
  }
}

const notInitialized = {}

if (notInitialized.parent.child) do-some-thing-cool
````

In node the above example will throw an exception that you are trying to access a property of undefined including stacktrace. When this exception is transformed to a Feathers FeneralError the details of the original exception are missing.

I hope this helps to pinpoint the problem.

**Comment by JackyW83** [comment]
Yes, this is very frustrating when debugging.

The stack only show like this:

```

 error: GeneralError: invalid input syntax for type date: "Invalid date"
     at new GeneralError (/var/www/school/node_modules/@feathersjs/errors/lib/index.js:170:17)
     at exports.errorHandler.error (/var/www/school/node_modules/feathers-sequelize/lib/utils.js:29:20)
     at tryCatcher (/var/www/school/node_modules/bluebird/js/release/util.js:16:23)
     at Promise._settlePromiseFromHandler (/var/www/school/node_modules/bluebird/js/release/promise.js:517:31)
     at Promise._settlePromise (/var/www/school/node_modules/bluebird/js/release/promise.js:574:18)
     at Promise._settlePromise0 (/var/www/school/node_modules/bluebird/js/release/promise.js:619:10)
     at Promise._settlePromises (/var/www/school/node_modules/bluebird/js/release/promise.js:695:18)
     at _drainQueueStep (/var/www/school/node_modules/bluebird/js/release/async.js:138:12)
     at _drainQueue (/var/www/school/node_modules/bluebird/js/release/async.js:131:9)
     at Async._drainQueues (/var/www/school/node_modules/bluebird/js/release/async.js:147:5)
     at Immediate.Async.drainQueues [as _onImmediate] (/var/www/school/node_modules/bluebird/js/release/async.js:17:14)
     at runCallback (timers.js:705:18)
     at tryOnImmediate (timers.js:676:5)
     at processImmediate (timers.js:658:5)
```

**Comment by edwardsmarkf** [comment]
what about going into various scripts such as '/var/www/school/node_modules/
feathers-sequelize/lib/utils.js" and putting a 'debugger' statement at line
170? you might be able to chase it up the stack that way.
or a "debugger" statement before you go into the sequelize call, and "step
into"...? i have noticed that sequelize is not overly picky on the date, at
least not with using MariaDB. but i try to stay with YYYY-MM-DD

Thank you,

Mark Edwards
