### ISSUE TITLE
Emit custom event in dynamic channel

### ISSUE THREAD

**Issue by matiaslopezd** [feathersjs/feathers#1293]
>You can [publish service specific](https://docs.feathersjs.com/api/channels.html#servicepublishevent-fn) events by returning the channels that you need. The data of the custom event should include the information that you need to identify the channel you want to send to (the connection information is available in a service call as [params.connection](https://docs.feathersjs.com/api/socketio.html#paramsconnection)):

```js
app.service('myservice').publish('notifyuser', data => {
  return app.channel(`socket/${data.userId}`);
});
```

_Originally posted by @daffl in https://github.com/feathersjs/feathers/issues/1236#issuecomment-469054034_

I'm trying to emit custom event in dynamic channel, but return error.

**channels.js**
```javascript
app.on('connection', connection => {
    if(connection.query.channel && connection.query.token){
      // Extract ID account
      let account = jwt.decode(connection.query.token, secret, false, 'HS256');
      account = hasher.decode(account.rac);
      const channel = `${account}/${connection.query.channel}`;
      
      // Join to dynamic channel
      app.channel(channel).join(connection);

      app.service('public/call').publish('queueupdate', data => {  <---- Here line 23
        console.log(data);
        return app.channel(channel);
      });
      
      app.service('public/call').publish('queueupdate', data => {
        return app.channel(channel).send({
          position: 99999
        });
      });
    }
  });
```

**log**
```shell
info: Feathers application started on http://localhost:3030
C:\xampp\htdocs\videsk-api\node_modules\@feathersjs\transport-commons\lib\channels\mixins.js:67
        throw new Error(`'${event}' is not a valid service event`);
        ^

Error: 'queueupdate' is not a valid service event
    at Object.publish (C:\xampp\htdocs\videsk-api\node_modules\@feathersjs\transport-commons\lib\channels\mixins.js:67:15)
    at Function.app.on.connection (C:\xampp\htdocs\videsk-api\src\channels.js:23:34)
    at Function.emit (events.js:182:13)
    at Namespace.provider.on.socket (C:\xampp\htdocs\videsk-api\node_modules\@feathersjs\transport-commons\lib\socket\index.js:17:11)
    at Namespace.emit (events.js:187:15)
    at Namespace.emit (C:\xampp\htdocs\videsk-api\node_modules\socket.io\lib\namespace.js:213:10)
    at C:\xampp\htdocs\videsk-api\node_modules\socket.io\lib\namespace.js:181:14
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! videsk-api@1.0.0 start: `node src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the videsk-api@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\matias\AppData\Roaming\npm-cache\_logs\2019-04-17T14_35_32_891Z-debug.log
```

Feathers version:
`3.9.0`

**Comment by daffl** [comment]
This applies only to [custom service events](https://docs.feathersjs.com/api/events.html#custom-events)

**Comment by matiaslopezd** [comment]
@daffl how can emit custom event to specific channel?

**Comment by daffl** [comment]
The channel name is usually determined from the `data` or `context` of the publisher. This means the `data` has to include the information to which channel it should go, for a specific user e.g. by having a `userId`:

```js
      app.service('public/call').publish('queueupdate', data => {  <---- Here line 23
        // Only emit to specific user channel
        return app.channel(`users/${data.userId}`);
      });
```

Custom events can be sent directly from the service as shown in the documentation (e.g. `app.service('public/call').emit('queueupdate', { userId: 1234, status: 'procesing' })`

**Comment by justraman** [comment]
@daffl i am also facing same issue.
````javascript
 //channel.ts
   app.service('dash-counters').publish('change', (data,hook) =>{
         return app.channel(`users/${hook.params.user.id}`)
   })
````
`
Error: 'change' is not a valid service event,
`
for service events like created, removed it's working fine. I also added event in service option but nothing works.
