### ISSUE TITLE
Feather server fails to start with Sequelize V6

### ISSUE THREAD

**Issue by trivedish** [feathersjs/feathers#1424]
### Steps to reproduce

Run the following command in order 
- feathers generate app
- feathers generate authentication, select Auth0, for the rest of the prompted questions
   - name of service : users
   - kind of service : Sequelize
   - database connecting to : PostgreSQL
- run `npm audit`

- [x] Tell us what broke. The more detailed the better.

`npm audit` shows the following problem with sequelize

```
                       === npm audit security report ===                        
                                                                                
Run  npm install sequelize@6.0.0  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ SQL Injection                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ sequelize                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ sequelize                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ sequelize                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1018                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


found 1 high severity vulnerability in 3143 scanned packages
  1 vulnerability requires semver-major dependency updates.
```

So we proceed ahead with recommendation to fix vulnerability and install Sequelize V6

- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
Running `npm start` post installing Sequalize v6 should have started the feathers server.

### Actual behavior

```
/Users/foo/workspace/f_demo1/node_modules/sequelize/lib/sequelize.js:322
      throw new Error('operatorAliases support was removed in v6');
      ^

Error: operatorAliases support was removed in v6
    at new Sequelize (/Users/foo/workspace/f_demo1/node_modules/sequelize/lib/sequelize.js:322:13)
    at Function.module.exports (/Users/foo/workspace/f_demo1/src/sequelize.js:5:21)
    at Function.configure (/Users/foo/workspace/f_demo1/node_modules/@feathersjs/feathers/lib/application.js:59:8)
    at Object.<anonymous> (/Users/foo/workspace/f_demo1/src/app.js:41:5)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/foo/workspace/f_demo1/src/index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): Sequelize V6

**NodeJS version**: 10.16.0

**Operating System**: macOS Catalina 10.15 Beta (19A487m)

**Browser Version**: Not applicable

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
Likely a duplicate of https://github.com/feathersjs/feathers/issues/1413. The latest version of `@feathersjs/cli` (`v3.9.0`) already generates a Sequelize connection without operator aliases and should work with v6.

**Comment by trivedish** [comment]
Thanks @daffl for quick response. I will try this out today.
