### ISSUE TITLE
Feathers v4 migration fails when I type the upgrade command

### ISSUE THREAD

**Issue by intumwa** [feathersjs/feathers#1432]
### Steps to reproduce

Hi Here, I have been following [this guide](https://crow.docs.feathersjs.com/migrating.html#migrating) to migrate to Feathers v4, but the command `feathers upgrade` fails with the error **AssertionError [ERR_ASSERTION]: When copying multiple files, provide a directory as destination**.  Below is the full display of the error.

$ feathers upgrade
events.js:173
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: When copying multiple files, provide a directory as destination
    at EditionInterface.exports.copy (C:\Users\username\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\mem-fs-editor\lib\actions\copy.js:36:5)
    at UpgradeGenerator.writing (C:\Users\username\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\generator-feathers\generators\upgrade\index.js:54:13)
    at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\yeoman-generator\lib\index.js:427:27)
    at C:\Users\username\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\username\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\username\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\yeoman-generator\lib\index.js:428:13)
    at processImmediate (timers.js:637:19)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\username\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\yeoman-generator\lib\index.js:436:22)
    at processImmediate (timers.js:637:19)

### System configuration
I am using Windows 10 and both Cygwin and CMD cannot run the above command. The NodeJS version is v11.10.0 and NPM is 6.9.0.

Thank you for guiding me, I have searched everywhere for a possible fix and couldn't find an answer.

**Comment by bloomdido** [comment]
I am having the same problem running Win 10 with WSL. Node version is 12.2.0 and npm 6.9.0.

**Comment by Garogat** [comment]
Same on linux.
```
node: v8.10.0
feathers: @feathersjs/cli@4.0.0-pre.2 
```

**Comment by daffl** [comment]
Should be fixed in `@feathersjs/cli@4.0.0-pre.3`
