### ISSUE TITLE
v4 custom oauth provider 

### ISSUE THREAD

**Issue by Garogat** [feathersjs/feathers#1452]
Adding a custom oauth provider works quite well in v4 until it reaches the getProfile() part. For that feathers uses `simov/grant-profile` package. Because grant-profile is using a hard-coded config of profile urls, login fails because the url of a custom provider can't be found.
[line of error](https://github.com/simov/grant-profile/blob/master/lib/client.js#L44)

I could use a custom OAuthStrategy, but it would be nice to somehow use grant-profiles helpers for custom providers aswell.

### Steps to reproduce
I have added my oauth provider to the default.json config:

```
{
...
  "authentication": {
...
    "oauth": {
      "redirect": "http://localhost:8080",
      "rzab": {
        "authorize_url": "https://auth.example.org/oauth2/authorize",
        "access_url": "https://auth.example.org/oauth2/token",
        "oauth": 2,
        "key": "OAUTH_CLIENT_ID",
        "secret": "OAUTH_CLIENT_SECRET",
        "scope": ["read", "write"],
        "nonce": true
      }
    }
  }
}
```

### Expected behavior
The profile url should be customizable.

### Actual behavior
```
backend_1        | error: TypeError: Cannot read property 'url' of undefined
backend_1        |     at Object.module.exports [as default] (/app/node_modules/grant-profile/lib/client.js:43:33)
backend_1        |     at OAuthStrategy.<anonymous> (/app/node_modules/@feathersjs/authentication-oauth/lib/strategy.js:52:36)
backend_1        |     at Generator.next (<anonymous>)
backend_1        |     at /app/node_modules/@feathersjs/authentication-oauth/lib/strategy.js:7:71
backend_1        |     at new Promise (<anonymous>)
backend_1        |     at __awaiter (/app/node_modules/@feathersjs/authentication-oauth/lib/strategy.js:3:12)
backend_1        |     at OAuthStrategy.getProfile (/app/node_modules/@feathersjs/authentication-oauth/lib/strategy.js:48:16)
backend_1        |     at OAuthStrategy.<anonymous> (/app/node_modules/@feathersjs/authentication-oauth/lib/strategy.js:113:40)
backend_1        |     at Generator.next (<anonymous>)
backend_1        |     at /app/node_modules/@feathersjs/authentication-oauth/lib/strategy.js:7:71

```

### System configuration

**Module versions** (especially the part that's not working):
```
"@feathersjs/authentication": "^4.0.0-pre.5",
"@feathersjs/authentication-oauth": "^4.0.0-pre.5",
"@feathersjs/express": "^4.0.0-pre.5",
"@feathersjs/feathers": "^4.0.0-pre.5",
```

**Comment by Garogat** [comment]
https://github.com/simov/grant-profile/issues/7

**Comment by daffl** [comment]
Wouldn't you also be able to customize the [getProfile](https://crow.docs.feathersjs.com/api/authentication/oauth.html#getprofile-data-params) call? Usually it's a call to the oAuth providers API:

```js
class MyCustomStrategy extends OAuthStrategy {
  async getProfile(data, params) {
    const { data } = axios.get({
      url: 'https://customprovider.com/oauth/user',
      headers: {
        Authorization: `Bearer: ${data.access_token}`
      }
    });

    return data;
  }
}
```

**Comment by Garogat** [comment]
Thanks @daffl using a custom Strategy works for me by now.

@simov will try to update `grant-profile` to directly support custom providers in the future.
