### ISSUE TITLE
Authentication throws error when using authentication.hooks.authenticate('jwt') 

### ISSUE THREAD

**Issue by crispinkoech** [feathersjs/feathers#1481]
Was attempting to set up an authentication hook for a service uing jwt : 

    export default {
        before: {
            create: [
                auth.hooks.authenticate('jwt'),
                // customHook(),
            ],
        },
        after: {},
        error: {},
    };

### Expected behavior
Application should authenticate a user given an access token via the Authorization error

### Actual behavior
A type error is thrown at JWT.verify: 
```
TypeError: this.service.get is not a function
    at JWTVerifier.verify (/home/crispin/Projects/Mali/mali.odin/node_modules/@feathersjs/authentication-jwt/lib/verifier.js:29:18)
    at /home/crispin/Projects/Mali/mali.odin/node_modules/passport-jwt/lib/strategy.js:121:34
    at /home/crispin/Projects/Mali/mali.odin/node_modules/jsonwebtoken/verify.js:223:12
    at getSecret (/home/crispin/Projects/Mali/mali.odin/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/home/crispin/Projects/Mali/mali.odin/node_modules/jsonwebtoken/verify.js:94:10)
    at Function.module.exports [as JwtVerifier] (/home/crispin/Projects/Mali/mali.odin/node_modules/passport-jwt/lib/verify_jwt.js:4:16)
    at /home/crispin/Projects/Mali/mali.odin/node_modules/passport-jwt/lib/strategy.js:104:25
    at JwtStrategy._secretOrKeyProvider (/home/crispin/Projects/Mali/mali.odin/node_modules/passport-jwt/lib/strategy.js:40:13)
    at JwtStrategy.authenticate (/home/crispin/Projects/Mali/mali.odin/node_modules/passport-jwt/lib/strategy.js:99:10)
    at Promise (/home/crispin/Projects/Mali/mali.odin/node_modules/@feathersjs/authentication/lib/passport/authenticate.js:105:18)
    at new Promise (<anonymous>)
    at /home/crispin/Projects/Mali/mali.odin/node_modules/@feathersjs/authentication/lib/passport/authenticate.js:13:14
    at Object.<anonymous> (/home/crispin/Projects/Mali/mali.odin/node_modules/@feathersjs/authentication/lib/hooks/authenticate.js:70:55)
    at promise.then.hookObject (/home/crispin/Projects/Mali/mali.odin/node_modules/@feathersjs/commons/lib/hooks.js:142:73)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

This is my current set up:
```
"@feathersjs/authentication": "^2.1.15",
"@feathersjs/authentication-jwt": "^2.0.10",
"@feathersjs/authentication-local": "^1.2.9"
"@feathersjs/configuration": "^2.0.6",
"@feathersjs/express": "^1.3.1",
"@feathersjs/feathers": "^3.3.1",
```
**NodeJS version**: 8.16.0

**Comment by daffl** [comment]
This looks like a misconfiguration in your application (most likely the `entity` service doesn't exist) but it is hard to tell without more information.

**Comment by crispinkoech** [comment]
Most likely a misconfiguration on my part. I am using a Custom Verifier class for my auth options after all.

I found out that this only came up when I set the `{entity}Id` field on the payload fields. Something like this throws the error described above:
```
const user = result.data;
const payload = {
    [`${this.options.entity}Id`]: user.id,
};
```
whereas this does not: 
```
const user = result.data;
const payload = {
    [`${this.options.entity}ID`]: user.id,
};
```

Note the difference between `Id` and `ID` in the two examples.
