### ISSUE TITLE
socketMap is undefined

### ISSUE THREAD

**Issue by fmoessle** [feathersjs/feathers#1645]
**Versions**
Node.js: 11.11.0
@feathersjs/express: 1.3.1
@feathersjs/feathers: 3.3.1
@feathersjs/socketio: 3.2.9

**Description**
When publishing events through a channel:
```javascript
app.publish((data, hook) => {
  return app.channel('authenticated')
})
```
I get the following error:

```javascript
TypeError: Cannot read property 'get' of undefined
    at channel.connections.forEach.connection (/Users/florian/Projects/kennzeichen-king/shop-api/node_modules/@feathersjs/transport-commons/lib/socket/utils.js:38:38)
    at Array.forEach (<anonymous>)
    at Function.<anonymous> (/Users/florian/Projects/kennzeichen-king/shop-api/node_modules/@feathersjs/transport-commons/lib/socket/utils.js:36:29)
    at Function.emit (events.js:197:13)
    at Function.EventEmitter.emit (domain.js:446:20)
    at Promise.resolve.then.result (/Users/florian/Projects/kennzeichen-king/shop-api/node_modules/@feathersjs/transport-commons/lib/channels/index.js:59:33)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

Turns out that socketMap is undefined in **/node_modules/@feathersjs/transport-commons/lib/socket/utils.js:38:38**

**Comment by daffl** [comment]
Make sure you have the latest `@feathersjs/commons` (by removing `node_modules` and `package-lock.json` and running `npm install` again).

**Comment by fmoessle** [comment]
Thanks! Solved the problem. Sometimes I want to kill all these lock-files :D
