### ISSUE TITLE
[v4] FeathersError type changed if used with disallow

### ISSUE THREAD

**Issue by bwgjoseph** [feathersjs/feathers#1695]
Hi,

My test broke after I upgrade to v4 when one of the test assert something like this `assert.ok(err instanceof FeathersError);`. It is now no longer true since v4.

### Steps to reproduce

I have this service `people`, with `disallow` hook in `before update`.

```
// Super simplified version
import * as commonHook from 'feathers-hooks-common';
const { disallow } = commonHook;

before: {
    all: [authenticate('jwt')],
    find: [],
    get: [],
    create: [],
    update: [disallow()],
    patch: [],
    remove: [],
  },
```

Run the test in `v4`

```
try {
      const data = await service.create(people) as People;
      await service.update(data._id, { name: 'people', description: 'people desc' });
    } catch (err) {
      console.log(err);
      assert.ok(err instanceof FeathersError);
    }
```

Output from `err`

```
{ MethodNotAllowed: Provider 'undefined' can not call 'update'. (disallow)
    at new MethodNotAllowed (...\node_modules\feathers-hooks-common\node_modules\@feathersjs\errors\lib\index.js:121:17)
    at Object.context (...\node_modules\feathers-hooks-common\lib\services\disallow.js:16:13)
    at current.then (...\node_modules\@feathersjs\commons\src\hooks.ts:132:47)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  type: 'FeathersError',
  name: 'MethodNotAllowed',
  message: 'Provider \'undefined\' can not call \'update\'. (disallow)',
  code: 405,
  className: 'method-not-allowed',
  data: undefined,
  errors: {},
```

However, the exact same thing work before the upgrade to `v4`.
More specifically, I'm using these version.

```
"@feathersjs/authentication-jwt": "^2.0.10",
"@feathersjs/authentication-local": "^1.2.9",
"@feathersjs/configuration": "^2.0.6",
"@feathersjs/errors": "^3.3.6",
"@feathersjs/express": "^1.3.1",
"@feathersjs/feathers": "^3.3.1",
"@feathersjs/socketio": "^3.2.9",
```

Any idea what is causing this? Is this intended?

Thanks.

**Comment by daffl** [comment]
The version of `feathers-hooks-commons` depends on a different version of `@feathersjs/errors`. I'd recommend either comparing `error.toJSON()` or just checking for `error.name`.

**Comment by bwgjoseph** [comment]
I see. Thanks.
