### ISSUE TITLE
only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by c10h22** [feathersjs/feathers#185]
Hi,

I am using feathers-errors in my mocha tests. I am using Gulp to watch changes in my tests sources and trigger gulp-mocha on each change. I just updated my feathersjs version (and feathers-errors by the way), and since that, I am getting the error below:

```
[23:51:46] Error in plugin 'gulp-mocha'
Message:
    only one instance of babel-polyfill is allowed
Stack:
Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (/Users/adnene/api_server/node_modules/feathers/node_modules/feathers-errors/node_modules/babel-polyfill/lib/index.js:8:9)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/adnene/api_server/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/adnene/api_server/node_modules/feathers/node_modules/feathers-errors/lib/index.js:22:1)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/adnene/api_server/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

If I stop watching my files, and run manually `gulp mocha` it works.
I tried to comment this line in `feathers-errors/lib/index.js`
```
require('babel-polyfill');
```
and magic, it works!

Could you please help me with issue, as I don't want to modify feathers-errors manually.

Reagards,
Adnene

**Comment by daffl** [comment]
Thank you for reporting this. I just released a v1.1.5 of feathers-errors which conditionally loads the Polyfill. If you clean the cache and reinstall the error should be gone.
