### ISSUE TITLE
Logout() generate "NotAuthenticated" errors when no user was logged in

### ISSUE THREAD

**Issue by yd021976** [feathersjs/feathers#1905]
### Steps to reproduce

On client side, just call "logout()" method of feathersjs auth client with no JWT/TOKEN stored (i.e. No user is logged in)

### Expected behavior
"logout()" should never throw exception, whenever a user was logged in or not

### Actual behavior
when "logout()" is called on client when no user is logged in (i.e. No JWT set), the feathersjs server throw exception as below
```
The trace in the FeathersJS server console :
error: NotAuthenticated: Invalid authentication information (no `strategy` set)
    at new NotAuthenticated (/Users/tigrou/www/backend-server/node_modules/@feathersjs/errors/lib/index.js:93:17)
    at Object.<anonymous> (/Users/tigrou/www/backend-server/node_modules/@feathersjs/authentication/lib/core.js:152:23)
    at Generator.next (<anonymous>)
    at /Users/tigrou/www/backend-server/node_modules/@feathersjs/authentication/lib/core.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/tigrou/www/backend-server/node_modules/@feathersjs/authentication/lib/core.js:4:12)
    at Object.authenticate (/Users/tigrou/www/backend-server/node_modules/@feathersjs/authentication/lib/core.js:143:16)
    at Object.<anonymous> (/Users/tigrou/www/backend-server/node_modules/@feathersjs/authentication/lib/service.js:110:25)
    at Generator.next (<anonymous>)
    at /Users/tigrou/www/backend-server/node_modules/@feathersjs/authentication/lib/service.js:8:71
```

### System configuration
**Module versions** (especially the part that's not working):
@feathersjs/authentication@^4.5.2
@feathersjs/feathers@4.5.2

**NodeJS version**:
v4.12.3.1

**Operating System**:
Mac OS catalina

**Browser Version**:
Chrome Version 80.0.3987.163

**Comment by daffl** [comment]
This is intended because the logout call (`app.service('authentication').remove()`) [verifies the token](https://docs.feathersjs.com/api/authentication/service.html#remove-id-params) and returns the logged out user information. As with most functionality you [can customize this behaviour](https://docs.feathersjs.com/api/authentication/service.html#customization) to what you need

```js
const { AuthenticationService } = require('@feathersjs/authentication');

class MyAuthService extends AuthenticationService {
  async remove (id, params) {
    try {
      return await super.remove(id, params);
    } catch(error) {
      if (error.name === 'NotAuthenticated') {
        return {};
      }

      throw error;
    }
  }
}

app.use('/authentication', new MyAuthService(app));
```
