### ISSUE TITLE
browserify to create a single bundle.js 

### ISSUE THREAD

**Issue by getforschin** [feathersjs/feathers#1973]
### Steps to reproduce

**npm install -g browserify

browserify src/index.js > bundle.js**

### Expected behavior
**bundle.js should be create to release my version in local network and i want integrated js with node_module**

### Actual behavior

**Error: Cannot find module 'hapi/package.json' from 'F:\DGQA_BACKEND\node_modules\grant'**
    at C:\Users\Lenovo\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\Lenovo\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
6.14.4
**NodeJS version**:
v12.16.3
**Operating System**:
windows
**Browser Version**:
chrome

**Comment by daffl** [comment]
Please provide a complete example to reproduce your issue.
