### ISSUE TITLE
README example failing due to feathers-nedb exception

### ISSUE THREAD

**Issue by alanrsoares** [feathersjs/feathers#209]
```
$ node app.js
```

```javascript
~/dev/feathers-test/node_modules/feathers-nedb/lib/index.js:43
			throw new Error('NeDB datastore `Model` needs to be provided');
			^

Error: NeDB datastore `Model` needs to be provided
    at new Service (~/dev/feathers-test/node_modules/feathers-nedb/lib/index.js:43:10)
    at init (~/dev/feathers-test/node_modules/feathers-nedb/lib/index.js:180:9)
    at Object.<anonymous> (~/dev/feathers-test/app.js:7:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by daffl** [comment]
It is indeed wrong. It's because you get the latest NeDB version which has the API changed. Since the release of version 2 is pretty close I just updated the homepage to run the `npm install` with specific version ranges.

```
npm install feathers@^1.3.0 body-parser feathers-nedb@^1.2.0
```

Should fix it.

**Comment by ekryski** [comment]
Yup. I'm gonna close this.
