### ISSUE TITLE
Feathers generate hook: UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'files' of undefined

### ISSUE THREAD

**Issue by Dahkenangnon** [feathersjs/feathers#2108]
### Steps to reproduce

**I have run the command: feathers generate hook**

### Expected behavior
Generating new hook

### Actual behavior
(Move up and down to reveal more choices)     
PS C:\Users\Dah-kenangnon\Music\e\apps\main\e_api> ^C
PS C:\Users\Dah-kenangnon\Music\e\apps\main\e_api> feathers generate hook   
(node:16344) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'files' of undefined
    at subloop (C:\Users\Dah-kenangnon\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\node-dir\lib\paths.js:92:58)      
    at C:\Users\Dah-kenangnon\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\node-dir\lib\paths.js:107:13
    at onDirRead (C:\Users\Dah-kenangnon\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\node-dir\lib\paths.js:139:35)   
    at onStat (C:\Users\Dah-kenangnon\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\node-dir\lib\paths.js:154:14)      
    at Object.files (C:\Users\Dah-kenangnon\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\node-dir\lib\paths.js:162:12)
    at HookGenerator._listServices (C:\Users\Dah-kenangnon\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\generator-feathers\generators\hook\index.js:11:23)
    at HookGenerator.prompting (C:\Users\Dah-kenangnon\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\generator-feathers\generators\hook\index.js:94:27)
    at Object.<anonymous> (C:\Users\Dah-kenangnon\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\yeoman-generator\lib\index.js:976:25)
    at C:\Users\Dah-kenangnon\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\Users\Dah-kenangnon\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\run-async\index.js:26:19
    at runLoop.add.once.once (C:\Users\Dah-kenangnon\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\yeoman-generator\lib\index.js:977:11)
    at processImmediate (internal/timers.js:456:21)
(node:16344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled 
promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). 
(rejection id: 2)
(node:16344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS C:\Users\Dah-kenangnon\Music\e\apps\main\e_api> 

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): 

The error occured when i ran: feathers generate hook.
  ```
"@feathersjs/authentication": "^4.5.8",
    "@feathersjs/authentication-local": "^4.5.8",
    "@feathersjs/authentication-oauth": "^4.5.8",
    "@feathersjs/configuration": "^4.5.8",
    "@feathersjs/errors": "^4.5.8",
    "@feathersjs/express": "^4.5.8",
    "@feathersjs/feathers": "^4.5.8",
    "@feathersjs/socketio": "^4.5.8",
    "@feathersjs/transport-commons": "^4.5.8",
```

**NodeJS version**: v12.18.3  && npm: 6.14.6

**Operating System**: Windows 10

**Module Loader**: default on browser

**Comment by corepay** [comment]
This happens to me now and then whrn I stop a generate process mid stream or move files around.  

I reinstall the cli and it has always cleared it up -  `npm install @feathersjs/cli -g`

**Comment by daffl** [comment]
This unfortunately is not easily reproducible. Make sure that

- You did not rename any folders manually
- All folders and files have the proper permission

Try to

- Reinstall the CLI as suggested
- Regenerate the application to see if the error persists in a brand new app
