### ISSUE TITLE
Server Crash when user leaves channels

### ISSUE THREAD

**Issue by camurai** [feathersjs/feathers#2133]
### Steps to reproduce
Setup a feathers server with SocketIO
(I am using OAuth with Discord but I am not sure if that is involved in this issue)

after authenticating, closing the page or reloading it triggers for the user to leave the socket channels

### Expected behavior
This should leave the channels for the user without issue

### Actual behavior
The server crashes with the following error:
TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at *projectpath*\node_modules\@feathersjs\transport-commons\src\channels\channel\combined.ts:14:6
    at Array.forEach (<anonymous>)
    at *projectpath*\node_modules\@feathersjs\transport-commons\src\channels\channel\combined.ts:8:25
    at Array.forEach (<anonymous>)
    at collectConnections (*projectpath*\node_modules\@feathersjs\transport-commons\src\channels\channel\combined.ts:7:12)
    at CombinedChannel.refresh (*projectpath*\node_modules\@feathersjs\transport-commons\src\channels\channel\combined.ts:43:17)
    at CombinedChannel.callChildren (*projectpath*\node_modules\@feathersjs\transport-commons\lib\channels\channel\combined.js:48:14)
    at CombinedChannel.leave (*projectpath*\node_modules\@feathersjs\transport-commons\src\channels\channel\combined.ts:48:4)
    at Function.leaveChannels (*projectpath*\node_modules\@feathersjs\transport-commons\src\socket\index.ts:25:8)

I put in a console log to the channels/combined code and found that the connection triggering the error is "keep-alive"

As a quick fix I have added a try/catch around the trouble code in \node_modules\@feathersjs\transport-commons\lib\channels\channel\combined.ts
but I am not sure if the failure to run this code properly is causing other issues.

### System configuration

**Module versions** (especially the part that's not working):
@feathersjs v4.5.10

**NodeJS version**:
v12.18.0

**Operating System**:
Windows 10

**Browser Version**:
Chrome  v86.0.4240.198

**Comment by daffl** [comment]
Please provide a complete repository that can reproduce your issue.

**Comment by camurai** [comment]
nevermind, I just found the cause of the issue and it was a mistake on my end. had some code in the channels.ts that was interfering with the user joining the authenticated channel (passing the wrong connection object), which was then causing this error later on. Thanks for the quick response though and sorry for wasting some of your time.

**Comment by tvld** [comment]
@camurai I am getting the same crash, but so far cant replicate it reliably.

What exactly did you do to avoid? 

Personally I think feathers should _warn_ when we pass a wrong channel parameter, not crash...
```
myApp/node_modules/@feathersjs/transport-commons/lib/channels/channel/combined.js:12
                mappings.set(connection, channel.data);
                         ^

TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at myApp/node_modules/@feathersjs/transport-commons/lib/channels/channel/combined.js:12:26
    at Array.forEach (<anonymous>)
    at myApp/node_modules/@feathersjs/transport-commons/lib/channels/channel/combined.js:9:29
    at Array.forEach (<anonymous>)
    at collectConnections (myApp/node_modules/@feathersjs/transport-commons/lib/channels/channel/combined.js:8:14)
    at new CombinedChannel (myApp/node_modules/@feathersjs/transport-commons/lib/channels/channel/combined.js:20:43)
    at Function.channel (myApp/node_modules/@feathersjs/transport-commons/lib/channels/mixins.js:43:20)
    at Function.channel (myApp/node_modules/@feathersjs/transport-commons/lib/channels/mixins.js:30:33)
    at Function.leaveChannels (myApp/node_modules/@feathersjs/transport-commons/lib/socket/index.js:17:21)
    at Function.emit (events.js:327:22)
    at Socket.<anonymous> (myApp/node_modules/@feathersjs/socketio/lib/middleware.js:4:39)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at Socket.emit (myApp/node_modules/socket.io/lib/socket.js:142:10)
    at Socket.onclose (myApp/node_modules/socket.io/lib/socket.js:454:8)
```

**Comment by tvld** [comment]
Ok, I can reproduce. My channel key depends name on an account:  `'account/${account._id}'`. If user deletes that account, the server crashes. So basically, deleting a channel that a user is subscribed to. I've not figured out why, but maybe the account becomes a promise or undefined.

**Comment by tvld** [comment]
@daffl my repository is quite big and this code badly isolated, so very time consuming to provide one. What can I do to help more beside that?

**Comment by daffl** [comment]
Please create a new issue. The most likely culprit if it is a Feathers issue would be doing something like `app.channel('something').join(undefined, null)` which should cause the same error.

**Comment by tvld** [comment]
See #2207
