### ISSUE TITLE
yo feathers:service: "Error: Cannot find module '../../lib/transform'"

### ISSUE THREAD

**Issue by abossard** [feathersjs/feathers#230]
Hi, 
I followed the getting started from here: http://docs.feathersjs.com/getting-started/quick-start.html for version 2.0 and selected "postgres" as databased. (everything else remained default).

This resulted in the following error, when I tried to create a serivce:

```
$ yo feathers:service
module.js:341
    throw err;
    ^

Error: Cannot find module '../../lib/transform'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-feathers/generators/service/index.js:4:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by abossard** [comment]
It's also like that when I use 'NeDB', so it has nothing to do with postgres.

node: 5.6.0
npm:  3.6.0
OS X: 10.10.5

**Comment by ekryski** [comment]
Yup I can reproduce. It's when you run `yo feathers:service`. Looking into it. Thanks for reporting @abossard!

**Comment by ekryski** [comment]
Should be all fixed now @abossard :smile:

**Comment by abossard** [comment]
Confirmed. Thanks you very much.
