### ISSUE TITLE
Quick Start Docs, curl example different, when Postgres is used.

### ISSUE THREAD

**Issue by abossard** [feathersjs/feathers#231]
I refer to: http://docs.feathersjs.com/getting-started/quick-start.html Step 7.

Current curl example:
```
curl 'http://localhost:3030/messages/' -H 'Content-Type: application/json' --data-binary '{ "text": "Hello Feathers!" }'
```
Fails with Postgres with this error:
```
info: BadRequest: Validation error: `text` must only contain alpha numeric characters
    at Object.construct (/Users/andre/Desktop/projects/feathers-chat/node_modules/core-js/modules/es6.reflect.construct.js:22:24)
    at BadRequest.ExtendableBuiltin (/Users/andre/Desktop/projects/feathers-chat/node_modules/feathers-errors/lib/index.js:27:28)
    at BadRequest.FeathersError (/Users/andre/Desktop/projects/feathers-chat/node_modules/feathers-errors/lib/index.js:105:87)
    at new BadRequest (/Users/andre/Desktop/projects/feathers-chat/node_modules/feathers-errors/lib/index.js:145:79)
    at errorHandler (/Users/andre/Desktop/projects/feathers-chat/node_modules/feathers-sequelize/lib/utils.js:28:25)
    at tryCatcher (/Users/andre/Desktop/projects/feathers-chat/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/andre/Desktop/projects/feathers-chat/node_modules/bluebird/js/release/promise.js:497:31)
    at Promise._settlePromise (/Users/andre/Desktop/projects/feathers-chat/node_modules/bluebird/js/release/promise.js:555:18)
    at Promise._settlePromise0 (/Users/andre/Desktop/projects/feathers-chat/node_modules/bluebird/js/release/promise.js:600:10)
    at Promise._settlePromises (/Users/andre/Desktop/projects/feathers-chat/node_modules/bluebird/js/release/promise.js:679:18)
    at Promise._reject (/Users/andre/Desktop/projects/feathers-chat/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._settlePromise (/Users/andre/Desktop/projects/feathers-chat/node_modules/bluebird/js/release/promise.js:570:21)
    at Promise._settlePromise0 (/Users/andre/Desktop/projects/feathers-chat/node_modules/bluebird/js/release/promise.js:600:10)
    at Promise._settlePromises (/Users/andre/Desktop/projects/feathers-chat/node_modules/bluebird/js/release/promise.js:679:18)
    at Promise._reject (/Users/andre/Desktop/projects/feathers-chat/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._settlePromise (/Users/andre/Desktop/projects/feathers-chat/node_modules/bluebird/js/release/promise.js:570:21)
error: (400) Route: /messages/ - Validation error: `text` must only contain alpha numeric characters
```

If I just use a single word (no space and no exclamation mark) it works:
```curl 'http://localhost:3030/messages' -H 'Content-Type: application/json' --data-binary '{ "text": "Hello3" ```}'

I suggest to change the example or to use different template parameters in the sequelize model.

**Comment by kulakowka** [comment]
If you create application with [generator-featers](https://github.com/feathersjs/generator-feathers),
You should change validation option from `isAlphaNumeric` to `isAlphanumeric` in your models: `/src/services/user/user-model.js`. There were mistake in generator. Now it's fixed. You should update generator from npm, too.

Before:
```javascript
let user = sequelize.define('user', {
    text: {
      type: Sequelize.STRING,
      allowNull: false,
      unique: true,
      validate: {
        isAlphaNumeric: { msg: '`text` must only contain alpha numeric characters' }
      }
    }
  }, {
    freezeTableName: true
  });
```

After:
```javascript
let user = sequelize.define('user', {
    text: {
      type: Sequelize.STRING,
      allowNull: false,
      unique: true,
      validate: {
        isAlphanumeric: { msg: '`text` must only contain alpha numeric characters' }
      }
    }
  }, {
    freezeTableName: true
  });
```

**Comment by kulakowka** [comment]
We fixed this typo in generator https://github.com/feathersjs/generator-feathers/pull/39

**Comment by abossard** [comment]
Thank you very much! Great!

**Comment by daffl** [comment]
That validation doesn't really make any sense anyway does it? A message text can be anything. I'm thinking we should remove it.

**Comment by ekryski** [comment]
@daffl ya it doesn't really make sense. It was only added to show how you can do validations. Realistically you'd probably be changing your model pretty quick anyway.
