### ISSUE TITLE
Official guides for Feathers.js doesn't work (broken generators)

### ISSUE THREAD

**Issue by pzoltowski** [feathersjs/feathers#2426]
### Steps to reproduce
I'm new to nodejs/javascript ecosystem so it's possible that I do something wrong but generally having difficulties with following the official guide - generators or some dependencies probably are not up to date or buggy.

"Quick start" worked all great but while following "Generating an app" generator crashes while executing:

```
pzo@ feathers-chat % feathers generate service
? What kind of service is it? NeDB
? What is the name of the service? messages
? Which path should the service be registered on? /messages
? Does the service require authentication? Yes
/usr/local/lib/node_modules/@feathersjs/cli/node_modules/generator-feathers/lib/generator.js:40
    return this.props.tester || (this.pkg.devDependencies.jest ? 'jest' : 'mocha');

TypeError: Cannot read property 'jest' of undefined
    at ServiceGenerator.get testLibrary [as testLibrary] (/usr/local/lib/node_modules/@feathersjs/cli/node_modules/generator-feathers/lib/generator.js:40:59)
    at ServiceGenerator.writing (/usr/local/lib/node_modules/@feathersjs/cli/node_modules/generator-feathers/generators/service/index.js:223:41)
    at Object.<anonymous> (/usr/local/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:991:25)
    at /usr/local/lib/node_modules/@feathersjs/cli/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/@feathersjs/cli/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/usr/local/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:992:11)
```

When changed from NeDB to in-memory error is the same. On the other hand when I tried to create a new feathers-chat with 'jest' instead of default 'mocha' test modules then scaffolded app cannot start:

```
pzo@ feathers-chat % feathers generate app
? Do you want to use JavaScript or TypeScript? JavaScript
? Project name feathers-chat
? Description
? What folder should the source files live in? src
? Which package manager are you using (has to be installed globally)? npm
? What type of API are you making? REST, Realtime via Socket.io
? Which testing framework do you prefer? Jest
? This app uses authentication Yes
? Which coding style do you want to use? ESLint
? What authentication strategies do you want to use? (See API docs for all 180+ supported oAuth providers) Username + Password (Loc
al)
? What is the name of the user (entity) service? users
? What kind of service is it? NeDB
? What is the database connection string? nedb://../data
   create package.json
   create config/default.json
   create public/favicon.ico
   create public/index.html
   create .editorconfig
   create src/app.hooks.js
   create src/channels.js
   create src/index.js
   create src/logger.js
   create src/middleware/index.js
   create src/services/index.js
   create .gitignore
   create README.md
   create src/app.js
   create test/app.test.js
   create .eslintrc.json
   create config/production.json
   create config/test.json
   create src/services/users/users.service.js
   create src/authentication.js
   create test/authentication.test.js
   create src/services/users/users.class.js
   create src/models/users.model.js
   create src/services/users/users.hooks.js
   create test/services/users.test.js
npm ERR! code ETARGET
npm ERR! notarget No matching version found for object-inspect@^1.9.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/patryk/.npm/_logs/2021-08-10T09_25_10_996Z-debug.log

added 9 packages, and audited 10 packages in 934ms

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

added 9 packages, and audited 19 packages in 945ms

3 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

up to date, audited 19 packages in 885ms

3 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
npm WARN deprecated @types/socket.io-parser@3.0.0: This is a stub types definition. socket.io-parser provides its own type definitions, so you do not need this installed.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

added 158 packages, and audited 177 packages in 2s

9 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @jest/console@^27.0.6.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/patryk/.npm/_logs/2021-08-10T09_25_18_957Z-debug.log


> feathers-chat@0.0.0 lint
> eslint src/. test/. --config .eslintrc.json --fix "--fix"

patryk@pzothink feathers-chat % npm start

> feathers-chat@0.0.0 start
> node src/

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@feathersjs/authentication'
Require stack:
- /Users/patryk/Developer/web/featherjs/feathers-chat/src/services/users/users.hooks.js
- /Users/patryk/Developer/web/featherjs/feathers-chat/src/services/users/users.service.js
- /Users/patryk/Developer/web/featherjs/feathers-chat/src/services/index.js
- /Users/patryk/Developer/web/featherjs/feathers-chat/src/app.js
- /Users/patryk/Developer/web/featherjs/feathers-chat/src/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/Users/patryk/Developer/web/featherjs/feathers-chat/src/services/users/users.hooks.js:1:26)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/patryk/Developer/web/featherjs/feathers-chat/src/services/users/users.hooks.js',
    '/Users/patryk/Developer/web/featherjs/feathers-chat/src/services/users/users.service.js',
    '/Users/patryk/Developer/web/featherjs/feathers-chat/src/services/index.js',
    '/Users/patryk/Developer/web/featherjs/feathers-chat/src/app.js',
    '/Users/patryk/Developer/web/featherjs/feathers-chat/src/index.js'
  ]
}
```

guide also was missing that seems eslint and nodemon has to be installed.

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

node --version
v16.6.1

npm --version
7.20.5

**Operating System**:
MacOS Catalina (10.15.7)

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by ktfth** [comment]
What is the version of your feathers cli?

**Comment by daffl** [comment]
I am not able to reproduce this with the same system setup and versions and have not seen seen it come up anywhere else. It looks like some kind of npm/proxy error on your side. Often, removing the `package-lock.json` and reinstalling can solve the problem. Using a different Node or npm version is also an avenue to try.
