### ISSUE TITLE
Fresh TypeScript Feathers app will not start

### ISSUE THREAD

**Issue by bartduisters** [feathersjs/feathers#2474]
### Steps to reproduce

Create a fresh Feathers application with TypeScript and Jest as options.

### Expected behavior
No typing issues.
Running `npm run dev` should work.

### Actual behavior
There are typing issues on several packages.
ts-node-dev is not installed, so `npm run dev` does not work.

### Fix
Steps to reproduce

```
npm i --save-dev @types/serve-favicon @types/compression @types/cors @types/jest @types/axios ts-node-dev shx typescript
```
I would expect this to automatically be installed when picking TypeScript and Jest.

**Comment by FossPrime** [comment]
I can't reproduce. You must be on @feathersjs/cli 4.5, given that you're using Jest. There have been a couple changes since you posted. ts-node-dev is installed to devDependencies...

```
? Do you want to use JavaScript or TypeScript? TypeScript
? Project name f-1
? Description
? What folder should the source files live in? src
? Which package manager are you using (has to be installed globally)? npm
? What type of API are you making? REST, Realtime via Socket.io
? Which testing framework do you prefer? Jest
? This app uses authentication Yes
? What authentication strategies do you want to use? (See API docs for all 180
+ supported oAuth providers) Username + Password (Local)
? What is the name of the user (entity) service? users
? What kind of service is it? NeDB
? What is the database connection string? nedb://../data
```

Perhaps try this [sandbox](https://codesandbox.io/s/feathers-crow-ulg6w) and see if you can spot the issue. run `D=/tmp/f1 && mkdir $D && cd $D && feathers g app`

**Comment by bartduisters** [comment]
```shell
   ~/Projects/code-coaching/test-feathers  feathers --version
4.5.0
   ~/Projects/code-coaching/test-feathers  feathers generate app
? Do you want to use JavaScript or TypeScript? TypeScript
? Project name test-feathers
? Description
? What folder should the source files live in? src
? Which package manager are you using (has to be installed globally)? npm
? What type of API are you making? REST, Realtime via Socket.io
? Which testing framework do you prefer? Jest
? This app uses authentication Yes
? What authentication strategies do you want to use? (See API docs for all 180+
supported oAuth providers) Username + Password (Local)
? What is the name of the user (entity) service? users
? What kind of service is it? NeDB
? What is the database connection string? nedb://../data
   create package.json
   create config/default.json
   create public/favicon.ico
   create public/index.html
   create .editorconfig
   create src/app.hooks.ts
   create src/channels.ts
   create src/declarations.d.ts
   create src/index.ts
   create src/logger.ts
   create src/middleware/index.ts
   create src/services/index.ts
   create .gitignore
   create README.md
   create src/app.ts
   create test/app.test.ts
   create tsconfig.json
   create jest.config.js
   create .eslintrc.json
   create config/production.json
   create config/test.json
   create src/services/users/users.service.ts
   create src/authentication.ts
   create test/authentication.test.ts
   create src/services/users/users.class.ts
   create src/models/users.model.ts
   create src/services/users/users.hooks.ts
   create test/services/users.test.ts
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 120 packages, and audited 121 packages in 818ms

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

up to date, audited 121 packages in 1s

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

added 2 packages, and audited 123 packages in 501ms

15 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

added 1 package, and audited 124 packages in 3s

15 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

added 9 packages, and audited 133 packages in 516ms

15 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

up to date, audited 133 packages in 607ms

15 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
npm WARN deprecated @types/socket.io-parser@3.0.0: This is a stub types definition. socket.io-parser provides its own type definitions, so you do not need this installed.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

added 87 packages, and audited 220 packages in 1s

18 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @jest/globals@^27.3.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/barry/.npm/_logs/2021-10-25T21_43_37_821Z-debug.log


> test-feathers@0.0.0 lint
> eslint src/. test/. --config .eslintrc.json --ext .ts --fix "--fix"

sh: eslint: command not found
   ~/Projects/code-coaching/test-feathers  npm run dev

> test-feathers@0.0.0 dev
> ts-node-dev --no-notify src/

sh: ts-node-dev: command not found
```

**Comment by FossPrime** [comment]
- Whats your package.json look like?
- does npx ts-node-dev work?
- Whats in `node_modules/.bin`?
- Are you on MacOS zsh or FreeBSD bash?
- Do you get the same issue in a docker debian container?
- What's your node version?

Here's what output with the same config should look like, aside from the busy port:
```
sandbox@sse-sandbox-blj2v:/tmp/f2$ feathers g app
? Do you want to use JavaScript or TypeScript? TypeScript
? Project name f-2
? Description
? What folder should the source files live in? src
? Which package manager are you using (has to be installed globally)? npm
? What type of API are you making? REST, Realtime via Socket.io
? Which testing framework do you prefer? Jest
? This app uses authentication Yes
? What authentication strategies do you want to use? (See API docs for all 180
+ supported oAuth providers) Username + Password (Local)
? What is the name of the user (entity) service? users
? What kind of service is it? NeDB
? What is the database connection string? nedb://../data
   create package.json
   create config/default.json
   create public/favicon.ico
   create public/index.html
   create .editorconfig
   create src/app.hooks.ts
   create src/channels.ts
   create src/declarations.d.ts
   create src/index.ts
   create src/logger.ts
   create src/middleware/index.ts
   create src/services/index.ts
   create .gitignore
   create README.md
   create src/app.ts
   create test/app.test.ts
   create tsconfig.json
   create jest.config.js
   create .eslintrc.json
   create config/production.json
   create config/test.json
   create src/services/users/users.service.ts
   create src/authentication.ts
   create test/authentication.test.ts
   create src/services/users/users.class.ts
   create src/models/users.model.ts
   create src/services/users/users.hooks.ts
   create test/services/users.test.ts
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 120 packages, and audited 121 packages in 4s

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

up to date, audited 121 packages in 554ms

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

added 2 packages, and audited 123 packages in 578ms

15 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

added 1 package, and audited 124 packages in 627ms

15 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

added 9 packages, and audited 133 packages in 682ms

15 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

up to date, audited 133 packages in 598ms

15 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
npm WARN deprecated @types/socket.io-parser@3.0.0: This is a stub types definition. socket.io-parser provides its own type definitions, so you do not need this installed.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It isrecommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It isrecommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

added 87 packages, and audited 220 packages in 2s

18 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

added 441 packages, and audited 661 packages in 13s

64 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.


> f-2@0.0.0 lint
> eslint src/. test/. --config .eslintrc.json --ext .ts --fix "--fix"


/tmp/f2/test/app.test.ts
  1:8  warning  'assert' is defined but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (0 errors, 1 warning)

sandbox@sse-sandbox-blj2v:/sandbox$ npm run test

> feathers-crow-ts45@0.0.0 test> yarn run lint && yarn run compile && yarn run jest

yarn run v1.22.17
$ eslint src/. test/. --config .eslintrc.json --ext .ts --fix=============
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.5.0-dev.20211025

Please only submit bug reports when using the officially supported version.

=============

/sandbox/test/app.test.ts
  1:8  warning  'assert' is defined but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (0 errors, 1 warning)

Done in 1.13s.
yarn run v1.22.17
$ shx rm -rf lib/ && tsc
Done in 10.68s.
yarn run v1.22.17
$ jest  --forceExit
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/sandbox/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///sandbox/jest.config.js:1:1
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async requireOrImportModule (/sandbox/node_modules/jest-util/build/requireOrImportModule.js:65:32)
    at async readConfigFileAndSetRootDir (/sandbox/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:109:22)
    at async readConfig (/sandbox/node_modules/jest-config/build/index.js:227:18)
    at async readConfigs (/sandbox/node_modules/jest-config/build/index.js:414:26)
    at async runCLI (/sandbox/node_modules/@jest/core/build/cli/index.js:220:59)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
sandbox@sse-sandbox-blj2v:/sandbox$ echo $PATH
/home/sandbox/.nvm/versions/node/v16.12.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
sandbox@sse-sandbox-blj2v:/sandbox$ cd /tmp/
sandbox@sse-sandbox-blj2v:/tmp$ mkdir feathers
sandbox@sse-sandbox-blj2v:/tmp$ cd feathers
sandbox@sse-sandbox-blj2v:/tmp/feathers$ cd ..
sandbox@sse-sandbox-blj2v:/tmp$ mv feathers f2
sandbox@sse-sandbox-blj2v:/tmp$ cd f2/
sandbox@sse-sandbox-blj2v:/tmp/f2$ feathers -g app
error: unknown option '-g'
sandbox@sse-sandbox-blj2v:/tmp/f2$ feathers g app
? Do you want to use JavaScript or TypeScript? TypeScript
? Project name f-2
? Description
? What folder should the source files live in? src
? Which package manager are you using (has to be installed globally)? npm
? What type of API are you making? REST, Realtime via Socket.io
? Which testing framework do you prefer? Jest
? This app uses authentication Yes
? What authentication strategies do you want to use? (See API docs for all 180
+ supported oAuth providers) Username + Password (Local)
? What is the name of the user (entity) service? users
? What kind of service is it? NeDB
? What is the database connection string? nedb://../data
   create package.json
   create config/default.json
   create public/favicon.ico
   create public/index.html
   create .editorconfig
   create src/app.hooks.ts
   create src/channels.ts
   create src/declarations.d.ts
   create src/index.ts
   create src/logger.ts
   create src/middleware/index.ts
   create src/services/index.ts
   create .gitignore
   create README.md
   create src/app.ts
   create test/app.test.ts
   create tsconfig.json
   create jest.config.js
   create .eslintrc.json
   create config/production.json
   create config/test.json
   create src/services/users/users.service.ts
   create src/authentication.ts
   create test/authentication.test.ts
   create src/services/users/users.class.ts
   create src/models/users.model.ts
   create src/services/users/users.hooks.ts
   create test/services/users.test.ts
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 120 packages, and audited 121 packages in 4s

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

up to date, audited 121 packages in 554ms

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

added 2 packages, and audited 123 packages in 578ms

15 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

added 1 package, and audited 124 packages in 627ms

15 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

added 9 packages, and audited 133 packages in 682ms

15 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

up to date, audited 133 packages in 598ms

15 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
npm WARN deprecated @types/socket.io-parser@3.0.0: This is a stub types definition. socket.io-parser provides its own type definitions, so you do not need this installed.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It isrecommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It isrecommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

added 87 packages, and audited 220 packages in 2s

18 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

added 441 packages, and audited 661 packages in 13s

64 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.


> f-2@0.0.0 lint
> eslint src/. test/. --config .eslintrc.json --ext .ts --fix "--fix"


/tmp/f2/test/app.test.ts
  1:8  warning  'assert' is defined but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (0 errors, 1 warning)

sandbox@sse-sandbox-blj2v:/tmp/f2$ npm run test

> f-2@0.0.0 test
> npm run lint && npm run compile && npm run jest


> f-2@0.0.0 lint
> eslint src/. test/. --config .eslintrc.json --ext .ts --fix


/tmp/f2/test/app.test.ts
  1:8  warning  'assert' is defined but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (0 errors, 1 warning)


> f-2@0.0.0 compile
> shx rm -rf lib/ && tsc


> f-2@0.0.0 jest
> jest  --forceExit

ts-jest[ts-compiler] (WARN) test/app.test.ts:33:12 - error TS2571: Object is o
f type 'unknown'.

33     expect(data.indexOf('<html lang="en">')).not.toBe(-1);
              ~~~~
test/app.test.ts:47:17 - error TS2339: Property 'response' does not exist on t
ype 'unknown'.

47         const { response } = error;
                   ~~~~~~~~
test/app.test.ts:60:17 - error TS2339: Property 'response' does not exist on type 'unknown'.

60         const { response } = error;
                   ~~~~~~~~
 PASS  test/services/users.test.ts (26.988 s)
 PASS  test/authentication.test.ts (27.7 s)
  ● Console

    console.log
      Publishing all events to all authenticated users. See `channels.ts` and
https://docs.feathersjs.com/api/channels.html for more information.

      at src/channels.ts:48:13
          at Array.forEach (<anonymous>)

    console.log
      Publishing all events to all authenticated users. See `channels.ts` andhttps://docs.feathersjs.com/api/channels.html for more information.

      at src/channels.ts:48:13
          at Array.forEach (<anonymous>)

 FAIL  test/app.test.ts (31.959 s)
  ● Feathers application tests (with jest) › starts and shows the index page

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is
a long-running test."

      17 |   let server: Server;
      18 |
    > 19 |   beforeAll(done => {
         |   ^
      20 |     server = app.listen(port);
      21 |     server.once('listening', () => done());
      22 |   });

      at test/app.test.ts:19:3
      at Object.<anonymous> (test/app.test.ts:16:1)

  ● Feathers application tests (with jest) › 404 › shows a 404 HTML page

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this isa long-running test."

      17 |   let server: Server;
      18 |
    > 19 |   beforeAll(done => {
         |   ^
      20 |     server = app.listen(port);
      21 |     server.once('listening', () => done());
      22 |   });

      at test/app.test.ts:19:3
      at Object.<anonymous> (test/app.test.ts:16:1)

  ● Feathers application tests (with jest) › 404 › shows a 404 JSON error without stack trace

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this isa long-running test."

      17 |   let server: Server;
      18 |
    > 19 |   beforeAll(done => {
         |   ^
      20 |     server = app.listen(port);
      21 |     server.once('listening', () => done());
      22 |   });

      at test/app.test.ts:19:3
      at Object.<anonymous> (test/app.test.ts:16:1)


  ● Test suite failed to run

    listen EADDRINUSE: address already in use 0.0.0.0:3030

      18 |
      19 |   beforeAll(done => {
    > 20 |     server = app.listen(port);
         |                  ^
      21 |     server.once('listening', () => done());
      22 |   });
      23 |

      at Function.listen (node_modules/express/lib/application.js:618:24)
      at Function.listen (node_modules/@feathersjs/express/lib/index.js:61:34)
      at Function.newMethod (node_modules/uberproto/lib/proto.js:34:20)
      at Function.listen (node_modules/@feathersjs/socketio/lib/index.js:39:25)
      at Function.newMethod [as listen] (node_modules/uberproto/lib/proto.js:34:20)
      at test/app.test.ts:20:18

  ● Test suite failed to run

    Server is not running.



Test Suites: 1 failed, 2 passed, 3 total
Tests:       3 failed, 3 passed, 6 total
Snapshots:   0 total
Time:        32.906 s
Ran all test suites.
Force exiting Jest: Have you considered using `--detectOpenHandles` to detect
async operations that kept running after all tests finished?
sandbox@sse-sandbox-blj2v:/tmp/f2$
```

**Comment by daffl** [comment]
This should be fixed now via https://github.com/feathersjs/generator-feathers/pull/633 and is availble in the latest `@feathersjs/cli`
