### ISSUE TITLE
`feathers generate hook` fails in TypeScript project

### ISSUE THREAD

**Issue by ArthurClemens** [feathersjs/feathers#2503]
### Steps to reproduce

Create a new app using The Feathers Guide. Proceed with the CLI commands:
- `feathers generate app` - with [settings](https://docs.feathersjs.com/guides/basics/generator.html#generating-the-application) (choose TypeScript)
- `feathers generate service` - with [settings](https://docs.feathersjs.com/guides/basics/generator.html#generating-the-application)
- `feathers generate hook`  with [settings](https://docs.feathersjs.com/guides/basics/hooks.html#sanitize-new-message) 

### Expected behavior

- CLI command should respond with a success message `create src/hooks/process-message.ts`
- Folder `hooks` is created with file `process-message.ts`
- File `src/services/messages/messages.hooks.ts` is updated

### Actual behavior

`feathers generate hook` fails with:

```
(node:4793) UnhandledPromiseRejectionWarning: SyntaxError: Missing semicolon. (37:1)
    at Object._raise (/Users/arthur/.nvm/versions/node/v14.17.0/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:541:17)
    at Object.raiseWithData (/Users/arthur/.nvm/versions/node/v14.17.0/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:534:17)
    at Object.raise (/Users/arthur/.nvm/versions/node/v14.17.0/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:495:17)
    at Object.semicolon (/Users/arthur/.nvm/versions/node/v14.17.0/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:3550:10)
    at Object.parseExportDefaultExpression (/Users/arthur/.nvm/versions/node/v14.17.0/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:14588:12)
    at Object.parseExport (/Users/arthur/.nvm/versions/node/v14.17.0/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:14486:31)
    at Object.parseExport (/Users/arthur/.nvm/versions/node/v14.17.0/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:833:11)
    at Object.parseStatementContent (/Users/arthur/.nvm/versions/node/v14.17.0/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:13460:27)
    at Object.parseStatement (/Users/arthur/.nvm/versions/node/v14.17.0/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:13352:17)
    at Object.parseBlockOrModuleBlockBody (/Users/arthur/.nvm/versions/node/v14.17.0/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:13941:25)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4793) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:4793) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

No files are being created or updated.

### System configuration

**NodeJS version**: v14.17.0

**Operating System**: macOS 12.0.1

**Browser Version**: n.a.

**React Native Version**: n.a.

**Module Loader**: n.a.

**Comment by wjswkvk208** [comment]
I have a same problem.
![generatehook](https://user-images.githubusercontent.com/16177277/145335278-dbcf2410-d50f-4989-ab3a-7320563f221d.jpg)

**Comment by Millenniunn** [comment]
I also have the same issue:

/usr/local/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:541
    const err = new SyntaxError(message);
                ^

SyntaxError: Missing semicolon. (37:1)
    at Object._raise (/usr/local/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:541:17)
    at Object.raiseWithData (/usr/local/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:534:17)
    at Object.raise (/usr/local/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:495:17)
    at Object.semicolon (/usr/local/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:3550:10)
    at Object.parseExportDefaultExpression (/usr/local/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:14588:12)
    at Object.parseExport (/usr/local/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:14486:31)
    at Object.parseExport (/usr/local/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:833:11)
    at Object.parseStatementContent (/usr/local/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:13460:27)
    at Object.parseStatement (/usr/local/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:13352:17)
    at Object.parseBlockOrModuleBlockBody (/usr/local/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:13941:25) {
  loc: Position { line: 37, column: 1 },
  pos: 631,
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'MissingSemicolon'

**Comment by daffl** [comment]
This will be fixed via https://github.com/feathersjs/generator-feathers/pull/647 once the tests are passing (which they are not at the moment for some reason).

If you remove the `as HooksObject` at the end your current `.hooks.ts` files it will also work already.
