### ISSUE TITLE
 throw new Error(`'${method}' is not a valid hook method`);

### ISSUE THREAD

**Issue by andysay** [feathersjs/feathers#2611]
ℹ Preparing project for development                                                                                                                                                      09:54:49
ℹ Initial build may take a while                                                                                                                                                         09:54:49
/root/pax/node_modules/@feathersjs/feathers/lib/hooks/regular.js:122
                throw new Error(`'${method}' is not a valid hook method`);
                ^

Error: 'find' is not a valid hook method
    at /root/pax/node_modules/@feathersjs/feathers/lib/hooks/regular.js:122:23
    at Array.forEach (<anonymous>)
    at /root/pax/node_modules/@feathersjs/feathers/lib/hooks/regular.js:120:27
    at Array.forEach (<anonymous>)
    at createMap (/root/pax/node_modules/@feathersjs/feathers/lib/hooks/regular.js:115:24)
    at Service.regularHooks (/root/pax/node_modules/@feathersjs/feathers/lib/hooks/regular.js:163:21)
    at Service.service.hooks (/root/pax/node_modules/@feathersjs/feathers/lib/hooks/index.js:79:39)
    at Function.module.exports (/root/pax/src/server/services/mailer/mailer.service.js:22:11)
    at Function.configure (/root/pax/node_modules/@feathersjs/feathers/lib/application.js:43:18)
    at Function.module.exports (/root/pax/src/server/services/index.js:13:7)
    at Function.configure (/root/pax/node_modules/@feathersjs/feathers/lib/application.js:43:18)
    at Object.<anonymous> (/root/pax/src/server/app.js:93:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[nodemon] app crashed - waiting for file changes before starting...

whats a problem ?(

**Comment by daffl** [comment]
This probably means that you are trying to register a `find` hook on a service that does not have a `find` method (`feathers-mailer` only has a `create` method).

**Comment by andysay** [comment]
> This probably means that you are trying to register a `find` hook on a service that does not have a `find` method (`feathers-mailer` only has a `create` method).

thx for information
