### ISSUE TITLE
Fail to make a simple client/server application, socket.io version compatibility issue.

### ISSUE THREAD

**Issue by Leo843** [feathersjs/feathers#2635]
Hi, I am new to feathersjs and I try to make a simple server/client application using feathers with socket.io. I get an error when the client tries to connect to the server.

### Steps to reproduce

- Create a server application with `feathers generate app` (with Socket.IO API selected)
- Create a client node application with `yarn init` (or `npm`)
  - Install feathers client packages (as described [here](https://docs.feathersjs.com/api/client.html#node))
    - @feathersjs/feathers
    - @feathersjs/socketio-client
    - socket.io-client
  - Create a simple `index.js` file that tries to connect to the server socket.io
```
const io = require('socket.io-client');
const socket = io('http://localhost:3030')
socket.on('connect_error', console.error)
socket.on('error', console.error)
socket.on('connect', console.log('connected:', socket.connected))
```

When both applications run, the client fails to connect to the socket.io server with the following error:
```
Error: server error
    at Socket.onPacket (/home/leo/workspace/feathers-test/node_modules/engine.io-client/build/cjs/socket.js:341:33)
    at Polling.Emitter.emit (/home/leo/workspace/feathers-test/node_modules/@socket.io/component-emitter/index.js:143:20)
    at Polling.onPacket (/home/leo/workspace/feathers-test/node_modules/engine.io-client/build/cjs/transport.js:114:15)
    at callback (/home/leo/workspace/feathers-test/node_modules/engine.io-client/build/cjs/transports/polling.js:133:18)
    at Array.forEach (<anonymous>)
    at Polling.onData (/home/leo/workspace/feathers-test/node_modules/engine.io-client/build/cjs/transports/polling.js:136:77)
    at Request.Emitter.emit (/home/leo/workspace/feathers-test/node_modules/@socket.io/component-emitter/index.js:143:20)
    at Request.onLoad (/home/leo/workspace/feathers-test/node_modules/engine.io-client/build/cjs/transports/polling.js:388:18)
    at XMLHttpRequest.xhr.onreadystatechange (/home/leo/workspace/feathers-test/node_modules/engine.io-client/build/cjs/transports/polling.js:323:26)
    at Immediate._onImmediate (/home/leo/workspace/feathers-test/node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js:628:53) {
  code: 'parser error'
}
```

I found out that the server and the client use incompatible versions of socket.io. The server application uses socket.io version `2.4.1` and the client uses socket.io-client `4.5.0`. According to the socket.io [documentation](https://socket.io/docs/v4/client-installation/) these versions are not comaptible.

### Expected behavior

Using `feathers generate app` and instructions from feathersjs documentation should produce a working application.

### Actual behavior

Creating a straightforward server/client application by following feathersjs documentation produces an application that fails to communication through socket.io.

### System configuration

- server package.json
```
{
  "name": "feathers-server",
  "description": "",
  "version": "0.0.0",
  "homepage": "",
  "private": true,
  "main": "src",
  "keywords": [
    "feathers"
  ],
  "author": {
    "name": "****",
    "email": "****"
  },
  "contributors": [],
  "bugs": {},
  "directories": {
    "lib": "src",
    "test": "test/",
    "config": "config/"
  },
  "engines": {
    "node": "^16.0.0",
    "yarn": ">= 0.18.0"
  },
  "scripts": {
    "test": "yarn run lint && yarn run jest",
    "lint": "standard",
    "dev": "nodemon src/",
    "start": "node src/",
    "jest": "jest --forceExit"
  },
  "standard": {
    "env": [
      "jest"
    ],
    "ignore": []
  },
  "dependencies": {
    "@feathersjs/configuration": "^4.5.11",
    "@feathersjs/errors": "^4.5.11",
    "@feathersjs/express": "^4.5.11",
    "@feathersjs/feathers": "^4.5.11",
    "@feathersjs/socketio": "^4.5.11",
    "@feathersjs/transport-commons": "^5.0.0-pre.20",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "helmet": "^4.6.0",
    "serve-favicon": "^2.5.0",
    "winston": "^3.0.0"
  },
  "devDependencies": {
    "axios": "^0.27.2",
    "jest": "^28.1.0",
    "nodemon": "^2.0.15",
    "standard": "^17.0.0"
  }
}
```

- client package.json
```
{
  "name": "feathers-test",
  "version": "1.0.0",
  "main": "src/index.js",
  "license": "MIT",
  "dependencies": {
    "@feathersjs/feathers": "^5.0.0-pre.20",
    "@feathersjs/socketio-client": "^5.0.0-pre.20",
    "socket.io-client": "^4.5.0"
  }
}
```

**Comment by daffl** [comment]
With Feathers 4 you need to use `socket.io-client` version `^2.0.0`. You can also [migrate to the v5 prerelease](https://dove.docs.feathersjs.com/guides/migrating.html) which comes with support for the latest version of Socket.io.
