### ISSUE TITLE
Uncaught exception in the "request" rest-client

### ISSUE THREAD

**Issue by felipou** [feathersjs/feathers#2723]
I'm not sure how to reproduce this, but I got the following stack trace:

```
2022-08-17T23:04:59.656Z - error: uncaughtException: Cannot set property 'response' of undefined date=Wed Aug 17 2022 20:04:59 GMT-0300 (-03), pid=1, uid=1001, gid=1000, cwd=/app, execPath=/usr/local/bin/node, version=v10.1.0, argv=[/usr/local/bin/node, /app/main.js], rss=432848896, heapTotal=344707072, heapUsed=282751488, external=1753901, loadavg=[0.771484375, 0.83447265625, 0.48046875], uptime=54597028
TypeError: Cannot set property 'response' of undefined
    at Request._callback (/app/node_modules/@feathersjs/rest-client/lib/request.js:21:25)
    at Request.self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I checked the code where the exception occurred, and it really isn't handling the case where `data` is `undefined`.

https://github.com/feathersjs/feathers/blob/master/packages/rest-client/lib/request.js#L21

Not sure how that would be possible though. I'm using an old version of node.js, so maybe it's that. This code has been running frequently for a long time, and it's the first time I've seen this.

I'll replace the request client with the axios client anyway (this was already planned), but even so I decided to report this, so feel free to just close the issue!

### System configuration

**Module versions** (especially the part that's not working): @feathersjs/rest-client == 4.5.0

**NodeJS version**: v10.1

**Operating System**: Linux (nodejs docker image: node:10.1-stretch)

**Comment by daffl** [comment]
The `request` library has been [deprecated a while ago](https://github.com/request/request/issues/3142) and REST client support for it will be removed in Feathers v5 as well. I recommend switching to `fetch` as the client which should work without any other changes and will likely fix your issue.
