### ISSUE TITLE
SchemaWrapper.validate error when adding custom props to  default.json

### ISSUE THREAD

**Issue by tvld** [feathersjs/feathers#2758]
### Steps to reproduce

Any addition to ``default.json``, will throw an error. Example
```json
{ "test123" "This is a test",
  "host": "localhost",
  "port": 3030,
  "public": "./public/",
}
```
### Expected behavior
I assume we can use ``default.json`` for our own properties as well like we always did: include variables from ``.env`` and have different overriding config files for ``test.json`` and ``production.json``. If this is not the case anymore. I would expect some documentation how to handle own props...

### Actual behavior
Throws error:
``` 
/node_modules/@feathersjs/schema/src/schema.ts:50
      throw new BadRequest(error.message, error.errors)
            ^
BadRequest: validation failed
    at SchemaWrapper.validate (../myApp/node_modules/@feathersjs/schema/src/schema.ts:50:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Feathers.app.hooks.setup (../myApp/node_modules/@feathersjs/configuration/src/index.ts:28:13) {
  code: 400,
  className: 'bad-request',
  type: 'FeathersError',
  data: [
    {
      instancePath: '',
      schemaPath: '#/additionalProperties',
      keyword: 'additionalProperties',
      params: [Object],
      message: 'must NOT have additional properties'
    }
  ]
}
```
## Versions
Feathers: 5.0.0-pre.29 
Node: v16..17.0

**Comment by tvld** [comment]
Ok, going to close this as indeed there is [documentation](https://dove.feathersjs.com/api/configuration.html). It seems that we need to pay attention to the schema before using it as we did in the past. It's actually essential to do this for **all** upgrades from former FeathersJs apps, it seems
