### ISSUE TITLE
Quickstart code not compiling

### ISSUE THREAD

**Issue by tobi-or-not** [feathersjs/feathers#2830]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/crow/.github/contributing.md#report-a-bug))

- [ ] I followed the [quickstart](https://dove.feathersjs.com/guides/basics/starting.html) but cannot compile the code for the [second Part 'An API Server'](https://dove.feathersjs.com/guides/basics/starting.html#an-api-server)
- [ ] Install dependencies
```
npm init --yes
# Install TypeScript and its NodeJS wrapper
npm i typescript ts-node --save-dev
# Also initialize a TS configuration file that uses modern JavaScript
npx tsc --init --target es2020

npm install @feathersjs/feathers@pre --save
npm install @feathersjs/socketio@pre @feathersjs/koa@pre --save

```
- [ ] Run sample code from quickstart page `npx ts-node app.ts`
 
### Expected behavior
The server should start. Removing the dependency on `serveStatic`makes the example work just fine.

### Actual behavior
A TypeScript error is thrown:
```
Computer:feathers-quickstart-guide-test tobias$ npx ts-node app.ts
[...]/feathers-quickstart-guide-test/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
app.ts:2:47 - error TS2305: Module '"@feathersjs/koa"' has no exported member 'serveStatic'.

2 import { koa, rest, bodyParser, errorHandler, serveStatic } from '@feathersjs/koa'
                                                ~~~~~~~~~~~

    at createTSError ([...]/feathers-quickstart-guide-test/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError ([...]/feathers-quickstart-guide-test/node_modules/ts-node/src/index.ts:863:19)
    at getOutput ([...]/feathers-quickstart-guide-test/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile ([...]/feathers-quickstart-guide-test/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile ([...]/feathers-quickstart-guide-test/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] ([...]/feathers-quickstart-guide-test/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12) {
  diagnosticCodes: [ 2305 ]
}
```

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
```
{
  "name": "feathers-quickstart-guide-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "ts-node": "^10.9.1",
    "typescript": "^4.8.4"
  },
  "dependencies": {
    "@feathersjs/koa": "^5.0.0-pre.31",
    "@feathersjs/socketio": "^5.0.0-pre.31"
  }
```

**NodeJS version**:
v19.0.0, via nvm

**Operating System**:
MacOS 12.5.1 (21G83), Intel

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
This has been fixed with the release of `5.0.0-pre.32`. I pushed the guide updated before making the prerelease 😆
