### ISSUE TITLE
mssql config issue

### ISSUE THREAD

**Issue by jbridgenet** [feathersjs/feathers#2850]
Just installed the pre version, created an app using feathers client, selected MSSQL database.

then tried to Creating a migration:
npm run migrate:make -- chat

Got Errors:
npm run migrate:make -- chat

> f5api@0.0.0 migrate:make
> knex migrate:make chat

Requiring external module ts-node/register
knex: Unknown configuration option 'client' value tedious. Note that it is case-sensitive, check documentation for supported values.
Error: knex: Unknown configuration option 'client' value tedious. Note that it is case-sensitive, check documentation for supported values.
    at resolveConfig (/Users/jun/projects/jb1d/f5api/node_modules/knex/lib/knex-builder/internal/config-resolver.js:32:13)
    at knex (/Users/jun/projects/jb1d/f5api/node_modules/knex/lib/knex-builder/Knex.js:14:39)
    at Feathers.mssql (/Users/jun/projects/jb1d/f5api/src/mssql.ts:13:18)
    at Feathers.configure (/Users/jun/projects/jb1d/f5api/node_modules/@feathersjs/feathers/src/application.ts:52:14)
    at Object.<anonymous> (/Users/jun/projects/jb1d/f5api/src/app.ts:35:5)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module.m._compile (/Users/jun/projects/jb1d/f5api/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/jun/projects/jb1d/f5api/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:988:32)

traced back to node_modules/knex/lib/knex-builder/internal/config-resolver, found:
the client name "tedious" is NOT listed in the node_modules/knex/lib/constants.js:
const SUPPORTED_CLIENTS = Object.freeze(
  [
    'mssql',
    'mysql',
    'mysql2',
    'oracledb',
    'postgres',
    'pgnative',
    'redshift',
    'sqlite3',
    'cockroachdb',
    'better-sqlite3',
  ].concat(Object.keys(CLIENT_ALIASES))
);

In config/default.json:
  "mssql": {
    "client": **"tedious"**,
    "connection": "mssql://root:password@localhost:1433/f5api"
  },

**Comment by daffl** [comment]
Interesting, it looks like Knex didn't update their documentation accordingly since it still shows `tedious` there. Fixed in new apps via #2853.

You should be able to fix it in an existing application by changing the `client` configuration to `mssql` and running `npm install mssql`.
