### ISSUE TITLE
Can't generate a project

### ISSUE THREAD

**Issue by rottmann** [feathersjs/feathers#286]
When i press a key when it prompts for "Description" i got an error:

```
$ feathers generate
Feathers CLI


? Description 

readline.js:925
            throw err;
            ^

TypeError: Cannot read property 'emit' of undefined
    at Prompt.inquirer.prompt.prompts.(anonymous function).onKeypress (/home/rottmann/.nvm/versions/node/v4.4.1/lib/node_modules/feathers-cli/node_modules/vorpal/dist/ui.js:133:20)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/home/rottmann/.nvm/versions/node/v4.4.1/lib/node_modules/feathers-cli/node_modules/rx-lite/rx.lite.js:1535:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/rottmann/.nvm/versions/node/v4.4.1/lib/node_modules/feathers-cli/node_modules/rx-lite/rx.lite.js:1469:31)
    at AnonymousObserver.tryCatcher (/home/rottmann/.nvm/versions/node/v4.4.1/lib/node_modules/feathers-cli/node_modules/rx-lite/rx.lite.js:63:31)
    at AutoDetachObserverPrototype.next (/home/rottmann/.nvm/versions/node/v4.4.1/lib/node_modules/feathers-cli/node_modules/rx-lite/rx.lite.js:5782:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/rottmann/.nvm/versions/node/v4.4.1/lib/node_modules/feathers-cli/node_modules/rx-lite/rx.lite.js:1469:31)
    at AutoDetachObserver.tryCatcher (/home/rottmann/.nvm/versions/node/v4.4.1/lib/node_modules/feathers-cli/node_modules/rx-lite/rx.lite.js:63:31)
    at AutoDetachObserverPrototype.next (/home/rottmann/.nvm/versions/node/v4.4.1/lib/node_modules/feathers-cli/node_modules/rx-lite/rx.lite.js:5782:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/rottmann/.nvm/versions/node/v4.4.1/lib/node_modules/feathers-cli/node_modules/rx-lite/rx.lite.js:1469:31)
    at InnerObserver.onNext (/home/rottmann/.nvm/versions/node/v4.4.1/lib/node_modules/feathers-cli/node_modules/rx-lite/rx.lite.js:4306:29)

```

Fresh installed and updated Linux Mint 17.3
node 4.4.1
npm 3.8.3
feathers-cli 1.2.2
generator-feathers 0.7.0
generator-feathers-plugin 0.6.9
yo 1.7.0

Setup

- nvm
  `$  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash`
  `$  nvm install 4.4`
  `$  nvm use 4.4`

- feathersjs
  `$ npm install -g yo generator-feathers generator-feathers-plugin feathers-cli`

Run: `$ feathers generate`

**Comment by marshallswain** [comment]
Looks like the issue is happening inside the vorpal module.  Would you mind closing this one and opening the same issue in the feathers-cli repository?

**Comment by rottmann** [comment]
Ok
