### ISSUE TITLE
Cryptic error message in tutorial step 3.2:

### ISSUE THREAD

**Issue by llnathanll** [feathersjs/feathers#289]
I'm on [step 3.2 of the tutorial](http://docs.feathersjs.com/getting-started/user-management.html), and I get the following error when i try to start the server:

> ```
    module.js:340
    throw err;
    Error: Cannot find module 'feathers-memory'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/hunkajunk_ii/Projects/Realtime/Feathers/test/src/app.js:7:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

Please clarify what causes this or how it can be fixed.

**Comment by daffl** [comment]
`npm install feathers-memory --save` should fix the error. It looks like npm sometimes doesn't install all dependencies which usually can be fixed by re-running `npm install`. You did you select in-memory as the database correct?

**Comment by ekryski** [comment]
Yes I'm watching an issue on npm. There are a lot of people having problems with npm3 some times not installing modules. @daffl's answer will get your sorted :smile:.
