### ISSUE TITLE
Nodejs client batch service creating

### ISSUE THREAD

**Issue by 7NT** [feathersjs/feathers#2920]
The server side is the dove pre-release connected to a mssql.
```
Here is my nodejs client code:
const io = require('socket.io-client');
const feathers = require('@feathersjs/feathers');
const socketio = require('@feathersjs/socketio-client');
const fs = require('fs');

const socket = io('http://localhost:3030');
const client = feathers();

client.configure(socketio(socket));

const usersService = client.service('users');
usersService.on('created', user => console.log('Created a user', user));

const csvFileContents = fs.readFileSync('./src/qusers.csv', 'utf-8');
csvFileContents.split(/\r?\n/).forEach(async line =>  {
  let data = line.split(',')
  const userData = {
      username: data[1],
      password: data[2],
      email: data[3]
  }
  console.log(userData)  
  await usersService.create(userData)  
});
```
When I run:
`npm run test`

A test account 'someone' was created without issue.

When I run above nodejs js code for over 18000 records, I received : 'Canceled'
no record created in my database.

below is my package.json:
```
{
  "name": "sqlusers",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@feathersjs/feathers": "^4.5.15",
    "@feathersjs/socketio-client": "^4.5.15",
    "socket.io-client": "^2.0.0"
  }
}
```
I changed socket.io-client from v4.5.x to 2.0.0, because error:
```
throw new Error('socket.io-client must be version 2.x');
    ^

Error: socket.io-client must be version 2.x
    at socketioClient (C:\projects\sqlusers\node_modules\@feathersjs\socketio-client\lib\index.js:14:11)
    at Object.<anonymous> (C:\projects\sqlusers\src\index.js:9:18)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.0.0
```

**Comment by daffl** [comment]
If your server is the dove prerelease, the client dependencies should be the `@pre` release:

```
npm install @feathersjs/feathers@pre @feathersjs/socketio-client@pre socket.io-client
```
