### ISSUE TITLE
feathers generate authentication fails on typescript projects (Win11)

### ISSUE THREAD

**Issue by ericblade** [feathersjs/feathers#3411]
App generated with ```npm create feathers@latest grocy-micro-ui``` and Typescript selected.  See #3409 for additional hurdles that had to be overcome to get this far.

```
G:\grocy-micro-ui>npx feathers generate authentication
? What authentication strategies do you want to use? (See API docs for all 180+ supported oAuth providers) Username + Password (Local), Auth0, Google, Facebook, Twitter, GitHub
? What is the name of the user (entity) service? users
C:\Users\EricB\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\yeoman-generator\node_modules\mem-fs-editor\lib\actions\read.js:12
    throw new Error(filepath + ' doesn\'t exist');
          ^

Error: G:\grocy-micro-ui\src\app.js doesn't exist
    at module.exports [as read] (C:\Users\EricB\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\yeoman-generator\node_modules\mem-fs-editor\lib\actions\read.js:12:11)
    at AuthGenerator.writing (C:\Users\EricB\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\generator-feathers\generators\authentication\index.js:178:28)
    at Object.<anonymous> (C:\Users\EricB\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\yeoman-generator\lib\index.js:991:25)
    at C:\Users\EricB\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\Users\EricB\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\run-async\index.js:26:19
    at runLoop.add.once.once (C:\Users\EricB\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\yeoman-generator\lib\index.js:992:11)
    at Immediate.<anonymous> (C:\Users\EricB\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\grouped-queue\lib\subqueue.js:48:34)
    at process.processImmediate (node:internal/timers:478:21)

Node.js v20.10.0

G:\grocy-micro-ui>
```

**Comment by daffl** [comment]
This is probably related to your issue in https://github.com/feathersjs/feathers/discussions/3414. It looks like your app didn't generate properly (possibly due to a crash during installation or missing file permissions). Generating a new app might likely solve the problem.

**Comment by ericblade** [comment]
Yep, thank you.  Apologies!

Added further info to #3414
