### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by foxhound87** [feathersjs/feathers#389]
**feathers version**: `2.0.1`

Sometimes the service is unreachable from the server-side,
sometimes the page never ends to load, and sometimes I get the error, 
which only happen on server-side, no errors on client-side from the same code.

```
TypeError: Cannot read property 'replace' of undefined
   at stripSlashes (/node_modules/feathers-commons/lib/utils.js:19:14)
   at Object.service (/node_modules/feathers/lib/application.js:44:50)
   at service (app.js:27:16)
   at ListStore.find (list.js:124:12)
   at ListStore.load (list.js:54:17)
   at Function.fetchData (ListPage.jsx:26:23)
   at fetch.js:12:33
   at Array.map (native)
   at fetchData (fetch.js:12:6)
   at _default (ssr.js:21:3)
   at handleRouter (routing.js:5:35)
   at routing.js:26:25
   at /node_modules/react-router/lib/match.js:65:5
   at /node_modules/react-router/lib/createTransitionManager.js:118:11
   at done (/node_modules/react-router/lib/AsyncUtils.js:79:19)
   at /node_modules/react-router/lib/AsyncUtils.js:85:7
```

**Comment by daffl** [comment]
What is the code? It looks like it's passing a `servicename` that's not a string to `app.service(servicename)`

**Comment by foxhound87** [comment]
You are right, sorry, the service name was set dynamically, and sometimes it was not defined.
