### ISSUE TITLE
User Validation

### ISSUE THREAD

**Issue by rrubio** [feathersjs/feathers#511]
Hi Guys,

I'm able to login using the correct username/password for any user (perfect). When i try testing invalid logins i'm getting errors. I would expect something along the lines of:

NOTE: i'm using the standard "/auth/local" path as per tutorial.

`{status: 401, message: 'invalid user'}`

Instead i'm getting the following:

`error: (401) Route: /auth/local - Invalid login.
info: NotAuthenticated: Invalid login.
    at NotAuthenticated.ExtendableBuiltin (/www/feathersApp/node_modules/feathers-errors/lib/index.js:21:28)
    at NotAuthenticated.FeathersError (/www/feathersApp/node_modules/feathers-errors/lib/index.js:96:116)
    at new NotAuthenticated (/www/feathersApp/node_modules/feathers-errors/lib/index.js:149:117)
    at /www/feathersApp/node_modules/feathers-authentication/lib/services/local.js:153:27
    at allFailed (/www/feathersApp/node_modules/passport/lib/middleware/authenticate.js:94:18)
    at attempt (/www/feathersApp/node_modules/passport/lib/middleware/authenticate.js:167:28)
    at Strategy.strategy.fail (/www/feathersApp/node_modules/passport/lib/middleware/authenticate.js:284:9)
    at verified (/www/feathersApp/node_modules/passport-local/lib/strategy.js:82:30)
    at /www/feathersApp/node_modules/feathers-authentication/lib/services/local.js:112:18
    at process._tickCallback (internal/process/next_tick.js:103:7)`

**Comment by daffl** [comment]
To get JSON formatted errors you have to set up the `feathers-errors/handler` middleware [as documented here](https://docs.feathersjs.com/middleware/error-handling.html#error-handling).

**Comment by rrubio** [comment]
@daffl thank you, that middleware? will that go in my services/user/index.js?

**Comment by daffl** [comment]
It should be the last middleware in your `app.js`. The generator already sets it up in `middleware/index.js` (see [in this example](https://github.com/feathersjs/feathers-chat/blob/master/src/middleware/index.js#L18))

**Comment by rrubio** [comment]
Brilliant! thank you!
