### ISSUE TITLE
Up and running with Sequelize and Postgres

### ISSUE THREAD

**Issue by ccorcos** [feathersjs/feathers#517]
### Steps to reproduce

Just run feathers generate selecting Postgres, Sequelize, and local user auth. `npm start` didnt just work. 

Well then I realized I should install postgres: `brew install postgres`, then I figured out how to start postgres: `pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start`. 

Then I run `npm start` and I get the same error:

```
(node:20941) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
Feathers application started on localhost:3030
Unhandled rejection SequelizeBaseError: role "postgres" does not exist
    at /Users/chetcorcos/code/rock-solid-infra/backend/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:110:20
    at Connection.<anonymous> (/Users/chetcorcos/code/rock-solid-infra/backend/node_modules/pg/lib/client.js:185:5)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (/Users/chetcorcos/code/rock-solid-infra/backend/node_modules/pg/lib/connection.js:121:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

I went through the docs to see if I missed anything: https://docs.feathersjs.com/databases/sequelize.html

I made sure to `npm install pg pg-hstore` even though I dont see it imported anywhere. I went through the migrations stuff thinking I need an initial migration to create the user table, but when I got to creating the migration with sequelize, I got the same error.

So I'm not sure what I should be doing here to get Feathers up and running with Sequelize and Postgres. I'm pretty unfamiliar with this so I might be missing something that seems obvious, but I cant figure out what this error is telling me.

**Comment by ccorcos** [comment]
This got be closer: https://github.com/brianc/node-postgres/issues/1163#issuecomment-266161256

Now the error is just:

```
Feathers application started on localhost:3030
Unhandled rejection SequelizeBaseError: role "postgres" does not exist
    at /Users/chetcorcos/code/rock-solid-infra/backend/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:110:20
    at Connection.<anonymous> (/Users/chetcorcos/code/rock-solid-infra/backend/node_modules/pg/lib/client.js:185:5)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:189:7)
    at Socket.<anonymous> (/Users/chetcorcos/code/rock-solid-infra/backend/node_modules/pg/lib/connection.js:121:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

**Comment by daffl** [comment]
Looks like a Postgres configuration problem. Did you see [this Stackoverflow answer](http://stackoverflow.com/questions/15301826/psql-fatal-role-postgres-does-not-exist)?

**Comment by zusamann** [comment]
It is a postgres setup problem.

While trying to setup a connection like so: 
```js
let sequelize = new Sequelize('postgres://role:password@localhost:5432/dbname', databaseOptions);
```
You need to have a role (think of it like a user) in postgres setup. You can check/add/modify roles by using something like pgAdmin. Here is what it looks like on my end.

![image](https://cloud.githubusercontent.com/assets/12589797/22917478/2064fdba-f2ab-11e6-8737-360a825e89e3.png)

Now maybe what is happening here is you are connecting to your database like so:
```js
Sequelize('postgres://postgres:password@localhost:5432/dbname');
//                      ^^ this user is missing from your db
```

**Comment by ccorcos** [comment]
ah. no time right now -- this is a side project. but this looks like the issue -- I'll reopen if its still an issue.
