### ISSUE TITLE
basic test ->crash

### ISSUE THREAD

**Issue by interfaith** [feathersjs/feathers#553]
feathers generate app
/usr/lib/node_modules/feathers-cli/node_modules/generator-feathers/lib/generator.js:37
  _packagerInstall(... args) {
                   ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/app/index.js:3:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

mark@mark-VirtualBox:~/my-app$ node --version
v4.8.0
 lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04

**Comment by interfaith** [comment]
node was upgraded to v6 and worked ok

**Comment by marshallswain** [comment]
That is as expected.  Thanks!

**Comment by daffl** [comment]
I created a follow-up issue in https://github.com/feathersjs/feathers-cli/issues/79 to throw an error on Node versions older than 6
