### ISSUE TITLE
Authentication - Unique email Unhandled Rejection at: Promise Promise

### ISSUE THREAD

**Issue by cmburcus** [feathersjs/feathers#687]
I've been going through multiple issues closed and open as well as the documentation to the best of my ability. I am new to feathers and after 2 days of trying multiple ways of doing things, I have no idea what to do anymore.

Any help will be greatly appreciated. I thought the documentation was pretty straight forward but for some reason I simply cannot get it to work...

### Steps to reproduce

I am trying to create a user, but return an 400 error if a user with the same email already exists.

I have a react form (connecting through web socket). I created a hook called `unique-email` which i have included in my before -> create hook in the users service. (I'm using RethinkDB in case you're wondering)

```
const errors = require('feathers-errors');

module.exports = function (options = {}) { // eslint-disable-line no-unused-vars
  return function uniqueEmail (hook) {
    hook.app.service('users').find({
      email: hook.data.email,
      query:{ $limit: 0 }, // We don't actually care about the data
    })
      .then((results) => {
        if (results.total > 0) {
          throw new errors.BadRequest('Invalid', { errors: {
            email: 'Email already taken',
          } });
        }
      });

    return Promise.resolve(hook);
  };
};
```

The problem is, no matter what I do, i keep getting `error: Unhandled Rejection at: Promise  Promise { <rejected> { BadRequest: Invalid` instead of just throwing the error back to my frontend for it to do whatever it wants with it (in my case, display the error message)

**NOTE**: If in my hook i simply throw the error (so i don't check if users exist, i just throw it altogether), the correct response is sent to the frontend. (Except i kind of need to check...)

### Expected behavior
Return a 400 with {errors { email: email: 'Email already taken' }} and not create a new user

### Actual behavior

The user is created and returned successfully to the frontend. In my console, I receive the following error

```
feathers-socket-commons:methods Got 'users::create' event with connection { provider: 'socketio' } +10s
  feathers-authentication-local:hooks:hash-password Running hashPassword hook with options: { passwordField: 'password',
  entity: 'user',
  usernameField: 'email' } +0ms
  feathers-authentication-local:hooks:hash-password Hashing password. +1ms
info: after: users - Method: find
  feathers-errors BadRequest(400): Invalid +0ms
  feathers-errors { email: 'Email already taken' } +1ms
error: Unhandled Rejection at: Promise  Promise {
  <rejected> { BadRequest: Invalid
    at Error.BadRequest (/Users/Corado/persdev/budget/backend/node_modules/feathers-errors/lib/index.js:93:17)
    at hook.app.service.find.then (/Users/Corado/persdev/budget/backend/src/services/users/hooks/unique-email.js:11:26)
  type: 'FeathersError',
  name: 'BadRequest',
  message: 'Invalid',
  code: 400,
  className: 'bad-request',
  data: {},
  errors: { email: 'Email already taken' } } } BadRequest: Invalid
    at Error.BadRequest (/Users/Corado/persdev/budget/backend/node_modules/feathers-errors/lib/index.js:93:17)
    at hook.app.service.find.then (/Users/Corado/persdev/budget/backend/src/services/users/hooks/unique-email.js:11:26)
info: after: users - Method: create
  feathers-socket-commons:events Dispatching 1 event filters for 'created' event +669ms
  feathers-socket-commons:events Dispatching users created with data { createdAt: 2017-10-04T14:26:21.815Z,
  email: 'example@gmail.com',
  first_name: 'Test',
  id: 'e088dd8f-7642-4bed-a7de-0530ae984171',
  last_name: 'Test',
  password: '$2a$12$r.hY73d4S9H1QrhepQyMvefAPGDcH1FBcJo5IjT5fl.aosCYrZtsy',
  updatedAt: 2017-10-04T14:26:21.816Z } +0ms
info: after: users - Method: create
```

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** Latest install (i installed everything with the generators 3 days ago. Created app, added authentication with RethinkDB as the database)

**NodeJS version**: v6.9.5

**Operating System**: Mac OS Sierra

**Browser Version**: Chrome 60.0.3112.113

**Backend packages**:
```
"dependencies": {
    "body-parser": "^1.18.2",
    "compression": "^1.7.0",
    "cors": "^2.8.4",
    "feathers": "^2.2.0",
    "feathers-authentication": "^1.2.7",
    "feathers-authentication-hooks": "^0.1.4",
    "feathers-authentication-jwt": "^0.3.2",
    "feathers-authentication-local": "^0.4.4",
    "feathers-authentication-management": "^1.0.0",
    "feathers-configuration": "^0.4.1",
    "feathers-errors": "^2.9.2",
    "feathers-hooks": "^2.0.2",
    "feathers-hooks-common": "^3.7.3",
    "feathers-hooks-validate-joi": "^1.0.3",
    "feathers-rest": "^1.8.0",
    "feathers-rethinkdb": "^0.4.3",
    "feathers-socketio": "^2.0.0",
    "helmet": "^3.8.1",
    "rethinkdbdash": "^2.3.31",
    "serve-favicon": "^2.4.4",
    "winston": "^2.3.1"
  },
```

**Frontend feathers related packages**:
```
"feathers-authentication-client": "^0.3.3",
"feathers-client": "^2.4.0",
"socket.io-client": "^2.0.3",
```

**Comment by daffl** [comment]
`hook.app.service('users').find` returns a Promise. You have to `return` that Promise for the hook to know that it should wait:

```js
const errors = require('feathers-errors');

module.exports = function (options = {}) { // eslint-disable-line no-unused-vars
  return function uniqueEmail (hook) {
    return hook.app.service('users').find({
      email: hook.data.email,
      query:{ $limit: 0 }, // We don't actually care about the data
    })
    .then((results) => {
      if (results.total > 0) {
        throw new errors.BadRequest('Invalid', { errors: {
          email: 'Email already taken',
        } });
      }
    });
  };
};
```

**Comment by cmburcus** [comment]
@daffl Wow that was quite silly. Thanks a lot for the help. It makes a lot a sense
