### ISSUE TITLE
Errors caught show up in console

### ISSUE THREAD

**Issue by jarnojellesma** [feathersjs/feathers#713]
This project has 2 tests:

```
"Foods can be fetched when authenticated"

"can not be fetched when not authenticated"
```

The problem lies in the second test. It expects an error which is intercepted by a try / catch statemet. Therefore I don't expect the Error thrown in the console, yet it does.

The same problem applies using promises directly.

I have been digging in the source code of both Graphql and Feathers to solve this myself without success.

Minimum reproducable code: https://github.com/jarnojellesma/feathers-graphql-test-error

```
it ('can not be fetched when not authenticated', async () => {
  const api = apolloClient();

  try {
    const res = await api.query({ query });
  } catch (e) {
    return expect(e.graphQLErrors[0].message).to.equal('No auth token');
  }
  
  fail('foods can be fetched when not authenticated');
});
```

Output:

```
Test
info: after: users - Method: create
info: after: users - Method: find
info: after: authentication - Method: create
info: after: foods - Method: remove
    foods
info: after: foods - Method: create
info: after: foods - Method: create
info: after: foods - Method: create
info: after: users - Method: get
info: after: users - Method: get
info: after: foods - Method: find
      ✓ can be fetched when authenticated (81ms)
info: error: foods - Method: find: No auth token
error:  NotAuthenticated: No auth token
    at NotAuthenticated (/home/$USER/Desktop/examples/node_modules/feathers-errors/lib/index.js:100:17)
    at /home/$USER/Desktop/examples/node_modules/feathers-authentication/lib/hooks/authenticate.js:102:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
NotAuthenticated: No auth token
    at NotAuthenticated (/home/$USER/Desktop/examples/node_modules/feathers-errors/lib/index.js:100:17)
    at /home/$USER/Desktop/examples/node_modules/feathers-authentication/lib/hooks/authenticate.js:102:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
      ✓ can not be fetched when not authenticated

  'foods' service
    ✓ registered the service


  3 passing (1s)
```

**Comment by daffl** [comment]
This is from the [logging hook](https://github.com/feathersjs/feathers-chat/blob/master/src/hooks/logger.js#L4) that is generated with the application.  You can modify it to fit your needs or [remove it from the application hook file](https://github.com/feathersjs/feathers-chat/blob/master/src/app.hooks.js#L26).

**Comment by jarnojellesma** [comment]
Thanks for the fast response @daffl 

Unfortunately the error still appears after disabling the logger hook.

**Comment by daffl** [comment]
There's also the unhandled rejection handler at https://github.com/feathersjs/feathers-chat/blob/master/src/index.js#L8

**Comment by jarnojellesma** [comment]
Also doesn't fix it.

**Comment by daffl** [comment]
I verified that it is no longer printing the message by removing the error application hook in the chat application.

The reproducible example does not seem to work, it is referencing some modules in `../lib/testing/` which doesn't exist.

**Comment by jarnojellesma** [comment]
Ah right, I updated the repo. The lib now exists there. The problem may have something to do with the graphql or apollo layer.

**Comment by jarnojellesma** [comment]
hen we comment:

```
FeathersError.call(this, message, 'NotAuthenticated', 401, 'not-authenticated', data);
```
at: node_modules/feathers-errors/lib/index line 100

We get the output:

```
Test
    foods
      ✓ can be fetched when authenticated (63ms)
GraphQLError: Error
    at locatedError (/home/jarno/Desktop/feathers-graphql-test-error/node_modules/graphql/error/locatedError.js:23:10)
    at /home/jarno/Desktop/feathers-graphql-test-error/node_modules/graphql/execution/execute.js:547:55
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
      1) can not be fetched when not authenticated

  'foods' service
    ✓ registered the service


  2 passing (2s)
  1 failing

  1) Test
       foods
         can not be fetched when not authenticated:

      AssertionError: expected 'Error' to equal 'No auth token'
      + expected - actual

      -Error
      +No auth token
      
      at Context.it (test/app.test.js:55:54)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by daffl** [comment]
I don't think this has anything to do with Feathers. If you change your resolver to

```js
module.exports = {
  Query: {
    foods(root, args, { params, Foods }) {
      return Promise.reject(new Error('Dangit'));
    },
  }
};
```

The error still shows up in the console so it must be happening somewhere in the GraphQL module.

**Comment by jarnojellesma** [comment]
Alright, thanks for your time. Will look further in the Graphql community.
