### ISSUE TITLE
New services call a missing function "publish"

### ISSUE THREAD

**Issue by kokujin** [feathersjs/feathers#720]
I decided to port a version 2.x app to version 3. 

- I uninstalled the old feathers-cli and installed the generator for feathers version 3 applications.

-  I used the new CLI to generate an app and after that a test service.
If I start the application, "npm run start", I get the errors below

``````
npm run start            

> testapp@0.0.0 start /home/kokujin/Development/Research/testapp
> node src/

/home/kokujin/Development/Research/testapp/src/services/users/users.service.js:24
  app.publish(() => {
      ^

TypeError: app.publish is not a function
    at Function.module.exports (/home/kokujin/Development/Research/testapp/src/services/users/users.service.js:24:7)
    at Function.configure (/home/kokujin/Development/Research/testapp/node_modules/@feathersjs/feathers/lib/application.js:59:8)
    at Function.module.exports (/home/kokujin/Development/Research/testapp/src/services/index.js:3:7)
    at Function.configure (/home/kokujin/Development/Research/testapp/node_modules/@feathersjs/feathers/lib/application.js:59:8)
    at Object.<anonymous> (/home/kokujin/Development/Research/testapp/src/app.js:44:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
``````
I tried this 3 times, using different service names, twice using NeDB and once using MongoDB

Is anybody else having this problem? Thanks

**Comment by daffl** [comment]
Indeed, that [snuck in there](https://github.com/feathersjs/generator-feathers/blob/master/generators/service/templates/service.js#L24-L30) where it shouldn't be. I will update the template.

For now everything should work if you remove that section.
