### ISSUE TITLE
get does not work but find does.

### ISSUE THREAD

**Issue by musicformellons** [feathersjs/feathers#752]
Probably something simple/ stupid. When I do:
```
          app.service('users').find(
            { user_id: 2 }
          );
```
I get a result.

However doing:

```
          app.service('users').get(
            2
          );
```

gives following error:
```
info: error: users - Method: get: No record found for id '2'
error:  NotFound: No record found for id '2'
    at new NotFound (/home/usr/api_server/node_modules/feathers-errors/lib/index.js:121:17)
    at /home/usr/api_server/node_modules/feathers-sequelize/lib/index.js:175:15
    at tryCatcher (/home/usr/api_server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/usr/api_server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/usr/api_server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/usr/api_server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/usr/api_server/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/usr/api_server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/usr/api_server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/usr/api_server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

It looks like `get` does not use `user_id` but `id`. However in the user service I did set:
```
  const options = {
    name: 'users',
    id: 'user_id',
    Model,
    paginate
  };
```

**Comment by daffl** [comment]
What adapter/database is this using?

**Comment by musicformellons** [comment]
sequelize

**Comment by daffl** [comment]
My guess is it's a conversion issue. Try converting the id to an integer on the server to see if that works:

```js
app.service('users').hooks({
  before(context) {
    if(context.id) {
      context.id = parseInt(context.id, 10);
    }
  }
});
```

**Comment by musicformellons** [comment]
It's weird: Works now... Not clear what caused it/ solved it. Thanks anyway!
