### ISSUE TITLE
Can not get registered user after upgrading to Buzzard

### ISSUE THREAD

**Issue by musicformellons** [feathersjs/feathers#759]

**Comment by musicformellons** [comment]
Mmmh, somehow (probably because I commented out some auth hooks...dunno...?!) the fields are now created in the database, but I still get error:
```
index.js?3d97:109 Uncaught (in promise) 
NotFound {type: "FeathersError", name: "NotFound", message: "No record found for id '14'", code: 404, className: "not-found", …}
```

Following hook applies and might need to be different in buzzard?!:
```
module.exports = function (options = {}) { 
  return function (hook) {
    if (hook.params.query && (hook.params.query.include)) {
      const joinModel = hook.app.service('favorites_points').Model;
      const pointsModel = hook.app.service('points').Model;
      hook.params.sequelize = {
        raw: false,
        include: [{
          model: joinModel,
          as: 'FavPoints',
          include: [{
            model: pointsModel
          }]
        }]
      };
      delete hook.params.query.include;
    }

    return Promise.resolve(hook);
  };
};
```

**Comment by daffl** [comment]
Does it work if you remove the `restrict-to-owner` hook?

**Comment by musicformellons** [comment]
Then I get following error:
```
info: after: users - Method: get
* ************************************************before create *****************: 
type:before, method: create
data: { email: 'emailtest@mail.com',
  password: '$2a$12$Kwm7QP9f2Gi7hO.5ywmoMjHg50lnTq6' }
query: {}
params props: [ 'accessToken',
  'authenticated',
  'headers',
  'payload',
  'provider',
  'query',
  'route',
  'user' ]
info: error: users - Method: create: Validation error
error:  BadRequest: Validation error
    at new BadRequest (/home/usr/api_server/node_modules/@feathersjs/errors/lib/index.js:81:17)
    at errorHandler (/home/usr/api_server/node_modules/feathers-sequelize/lib/utils.js:13:25)
    at tryCatcher (/home/usr/api_server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/usr/api_server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/usr/api_server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/usr/api_server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/usr/api_server/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/usr/api_server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/usr/api_server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/usr/api_server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
info: after: authentication - Method: create
***************  hook.params.query AVAILABLE HERE?: { include: true }
info: after: users - Method: get
```

**Comment by daffl** [comment]
Can you please share a complete minimal example that reproduces the issue?

**Comment by musicformellons** [comment]
Now, after using the generator to get a template of Buzzard project, I made some additional changes but run into other/ additional/ similar errors. Will close this for now and open new issue.
