### ISSUE TITLE
Payload is undefined when trying to destructure userId. But on console.log it has a userId.

### ISSUE THREAD

**Issue by farebord** [feathersjs/feathers#760]
What im trying to do its limit user to access it own user data.
```
(context) =>  {
      console.log(context.params.payload)
      const { userId } = context.params.payload;
      const { userReqId } = context.result.id;
      if(userId !== userReqId)
        context.error = errors.Forbidden()
      return context
    }
```

console.log returns
```
{ userId: 1,
  iat: 1513799281,
  exp: 1513885681,
  aud: 'https://asdasd.com',
  iss: 'feathers',
  sub: 'anonymous',
  jti: '00d2aca3-7c28-4c3b-a061-4cc56d8e306f' }
```

const useriD returns an error
`error:  TypeError: Cannot destructure property `userId` of 'undefined' or 'null'.`

I don't understand why.

**Comment by daffl** [comment]
Are you absolutely sure this is the same hook context? I think it is more likely that this error is coming from a different one where `payload` is `undefined`.

My guess is what you really want to do is use the `authenticate('jwt')` hook first and then check if `hook.params.user._id === contest.result.id`.

**Comment by farebord** [comment]
Okey. I tried what you told me. 

After get hook looks like this:

```
after: {
    ...
    get: [ authenticate('jwt'), 
    (context) =>  {
      if(context.params.user._id !== context.result.id)
        context.error = errors.Forbidden()
      return context
    }],
    ...
    }
```

Same error (I tried both id and _id) :
`error:  TypeError: Cannot read property '_id' of undefined`

**Comment by daffl** [comment]
`authenticate('jwt')` needs to be a `before` hook. Then `params.user` will be available.

**Comment by farebord** [comment]
Right now code:

```
module.exports = {
  before: {
    all: [  populateUserId() ],
    find: [ authenticate('jwt') ],
    get: [ authenticate('jwt') ],
    create: [ hashPassword() ],
    update: [ authenticate('jwt'), hashPassword() ],
    patch: [ authenticate('jwt'), hashPassword() ],
    remove: [ disallow() ]
  },

  after: {
    all: [ 
      // Make sure the password field is never sent to the client
      // Always must be the last hook
      protect('password')
    ],
    find: [],
    get: [
    (context) =>  {
      console.log(context.params)
      console.log(context.result.id)
      if(context.params.user.id !== context.result.id)
        context.error = errors.Forbidden()
      return context
    }],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};
```

When I do '/users/2' it returns:
```
{
    "id": 2,
    "email": "prueba@prueba.com",
    "createdAt": "2017-12-20T18:27:37.000Z",
    "updatedAt": "2017-12-20T18:27:37.000Z"
}
```

On server console:
```
{}
1
error:  TypeError: Cannot read property 'id' of undefined
    at Object.module.exports.after.get (C:\Users\Facundo\Documents\MoveOn\moveon-backend\src\services\users\users.hooks.js:33:30)
    at <anonymous>
{ authenticated: true,
  query: {},
  route: {},
  provider: 'rest',
  headers:
   { 'cache-control': 'no-cache',
     'postman-token': '1a9a6df0-65b6-47ab-9736-67645e3db128',
     authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJ1c2VySWQiOjEsImlhdCI6MTUxMzg3NzA2OCwiZXhwIjoxNTEzOTYzNDY4LCJhdWQiOiJodHRwczovL21vdmVvbmFwcC5jb20iLCJpc3MiOiJmZWF0aGVycyIsInN1YiI6ImFub255bW91cyIsImp0aSI6ImQzMTQ4MDA0LTg4MzYtNDBmZS05MDMyLTJjNTdlMzY0NGUxMCJ9.VOxtQAl48Oo6aDLZYWCKQ79Qur_tLg3TDvrmXNoWcpk',
     'user-agent': 'PostmanRuntime/7.1.1',
     accept: '*/*',
     host: 'localhost:3030',
     'accept-encoding': 'gzip, deflate',
     connection: 'keep-alive' },
  user: {},
  payload:
   { userId: 1,
     iat: 1513877068,
     exp: 1513963468,
     aud: 'https://asdasd.com',
     iss: 'feathers',
     sub: 'anonymous',
     jti: 'd3148004-8836-40fe-9032-2c57e3644e10' } }
2
```

If I use payload:
```
info: Feathers application started on http://localhost:3030
undefined
1
error:  TypeError: Cannot read property 'userId' of undefined
    at Object.module.exports.after.get (C:\Users\Facundo\Documents\MoveOn\moveon-backend\src\services\users\users.hooks.js:33:33)
    at <anonymous>
{ userId: 1,
  iat: 1513877068,
  exp: 1513963468,
  aud: 'https://asdasd.com',
  iss: 'feathers',
  sub: 'anonymous',
  jti: 'd3148004-8836-40fe-9032-2c57e3644e10' }
2
```

I see on console.log the object payload exist and contains userId but when I try to access that with:
`if(context.params.payload.userId === context.result.id)` it returns error showed above.

**Comment by daffl** [comment]
What does `populateUserId` do?

**Comment by farebord** [comment]
```
const { disallow } = require('feathers-hooks-common')

module.exports = function (options = {}) { // eslint-disable-line no-unused-vars
  return context => {
    if(context.id === 'me') {
      context.id = context.params.user.id;
    }
  };
};

```

**Comment by daffl** [comment]
Ah, sorry, the user service is special because `authenticate('jwt')` will call make an additional call to `user.get(payload.userId)`. So basically you hook will run twice, the first time when populating `params.user` and then again for the actual call. You can conditionally run it by checking the provider:

```js
(context) =>  {
  if(!params.provider) { // Skip if it is an internal call
    return context;
  }

  console.log(context.params)
  console.log(context.result.id)
  if(context.params.user.id !== context.result.id)
    context.error = errors.Forbidden()
  return context
}
```

**Comment by farebord** [comment]
That worked. Thanks for the help! 👍
