### ISSUE TITLE
Server-side seeding error

### ISSUE THREAD

**Issue by 24thsaint** [feathersjs/feathers#805]
I have this seeding configuration:

```javascript
// seeder.js
async function seeder(app) {
  const userService = app.service('api/users');
  const results = await userService.find()
  if (results.length === 0) {
      // ... do more stuff
  }
}

export default seeder;
```

And I am calling it in:

```javascript
// app.js
const app = feathers();
app.configure(hooks());
app.configure(mongodb);
app.configure(rest());
app.configure(socketio());
app.configure(middleware);
app.configure(authentication);
app.configure(authManagement);
app.configure(services);
seederConfig(app); // <---- here
// ...
```

But when I run the application, I am receiving:

```bash
error: Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: Cannot read property 'find' of undefined
    at Object._find (/mnt/d/ornix-software/node_modules/feathers-mongodb/lib/index.js:106:25)
    at Object.find (/mnt/d/ornix-software/node_modules/feathers-mongodb/lib/index.js:160:25)
    at /mnt/d/ornix-software/node_modules/feathers-hooks/lib/hooks.js:101:31
    at Promise (<anonymous>)
    at /mnt/d/ornix-software/node_modules/feathers-hooks/lib/hooks.js:85:16
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3 } TypeError: Cannot read property 'find' of undefined
    at Object._find (/mnt/d/ornix-software/node_modules/feathers-mongodb/lib/index.js:106:25)
    at Object.find (/mnt/d/ornix-software/node_modules/feathers-mongodb/lib/index.js:160:25)
    at /mnt/d/ornix-software/node_modules/feathers-hooks/lib/hooks.js:101:31
    at Promise (<anonymous>)
    at /mnt/d/ornix-software/node_modules/feathers-hooks/lib/hooks.js:85:16
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
```

This is how I configure my services:
```javascript
// setupService.js
import createService from 'feathers-mongodb';

function setupService(name, hooks, filters, options = {}) { // filters is optional
  return function setupPlugin() {
    const app = this;
    const mongoClient = app.get('mongoClient');

    app.use(`api/${name}`, createService(options));

    const service = app.service(`api/${name}`);

    mongoClient.then((db) => {
      service.Model = db.collection(name);
    });

    service.hooks(hooks);

    if (filters && service.filter) {
      service.filter(filters);
    }
  };
}

export default setupService;
```

An example of the call

```javascript
// users.service.js
import setupService from '../setupService';
import hooks from './users.hooks';
import filters from './users.filters';

function configureService() {
  const app = this;
  const paginate = app.get('paginate');
  const options = { paginate };

  app.configure(setupService('users', hooks, filters, options));
}

export default configureService;
```

### Expected behavior
It should execute find with no problems. I have tried using feeathers-seeder and the same error occurs.

Note: Everything is working in the client perfectly.

### Actual behavior
I am receiving

>   <rejected> TypeError: Cannot read property 'find' of undefined

### System configuration

**Module versions** (especially the part that's not working):
"feathers": "^2.1.4",
"feathers-mongodb": "^2.9.0",

**NodeJS version**:
Node v8.5.0

**Operating System**:
Windows 10 Pro Insider Preview
Build 17074

**Comment by daffl** [comment]
Looks like it should work. What does `console.log(Object.keys(app.services))` show when you put it in the `async function seeder(app) {` function?

**Comment by 24thsaint** [comment]
Thank you for the swift reply!

This is the output
```bash
[ 'api/uploads',
  'authentication',
  'authManagement',
  'api/users',
  'api/farms',
  'api/trees',
  'api/areas',
  'api/activities' ]

**Comment by 24thsaint** [comment]
This happens only for the `find()` method. `create() and friends` work fine.

**Comment by daffl** [comment]
Ah, the error is in `feathers-mongodb`. I bet it'll work if you wait for the MongoDB client to connect.

```js
// seeder.js
async function seeder(app) {
  // Wait for MongoDB to connect
  await app.get('mongoClient');

  const userService = app.service('api/users');
  const results = await userService.find()
  if (results.length === 0) {
      // ... do more stuff
  }
}

export default seeder;
```

**Comment by 24thsaint** [comment]
WHOA! OMG. This worked! Thank you very much sir! 

I'm closing this now. 😍
