### ISSUE TITLE
Trying to use FeathersJS with `mongoose-update-if-current` to solve concurrency issues

### ISSUE THREAD

**Issue by benedictkohtc** [feathersjs/feathers#806]
Context: https://github.com/eoin-obrien/mongoose-update-if-current/issues/1

```
<somePath>\node_modules\mongoose\lib\schema.js:1212
    throw new Error('First param to `schema.plugin()` must be a function, ' +
    ^

Error: First param to `schema.plugin()` must be a function, got "object"
    at Schema.plugin (<somePath>\node_modules\mongoose\lib\schema.js:1212:11)
    at Mongoose._applyPlugins (<somePath>\node_modules\mongoose\lib\index.js:483:12)
    at Mongoose.model (<somePath>\node_modules\mongoose\lib\index.js:396:10)
    at module.exports (<somePath>\src\models\admin.model.js:21:24)
    at Function.module.exports (<somePath>\src\services\admin\admin.service.js:7:17)
    at Function.configure (<somePath>\node_modules\@feathersjs\feathers\lib\application.js:59:8)
    at Function.module.exports (<somePath>\src\services\index.js:47:6)
    at Function.configure (<somePath>\node_modules\@feathersjs\feathers\lib\application.js:59:8)
    at Object.<anonymous> (<somePath>\src\app.js:79:5)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (<somePath>\src\index.js:3:13)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by daffl** [comment]
This looks like a Mongoose error. Were you able to set this up with plain Mongoose without Feathers?

**Comment by benedictkohtc** [comment]
The repo came with tests which passes on my environment
``` PASS  __tests__\update-if-current-plugin.spec.ts
  updateIfCurrentPlugin
    √ should manage concurrency when saving documents (550ms)
    √ should handle documents with custom version keys (153ms)
    √ should handle documents with disabled version keys (123ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        3.719s, estimated 24s
Ran all test suites.```

**Comment by benedictkohtc** [comment]
Interesting, so I tried implementing it on a barebones express mongoose/mongoDB stack and got a similar error, I suspect its due to how I have plugged it to mongoose, will update back here again.

**Comment by benedictkohtc** [comment]
Okay the earlier error has been resolved, it was due to a require vs import syntax issue. 
How do I use this custom plugin from Feathers?

**Comment by daffl** [comment]
Feathers doesn't really do anything special with Mongoose. I would say open the `model` file and add the plugin as documented.

**Comment by benedictkohtc** [comment]
@daffl I have added the plugin globally, and also added a console.log within the plugin itself, its somehow not being fired.

1) Could you elaborate how does a feathers myService.patch() work behind the scenes? What mongoose method is it calling?
2) Does FeathersJS handle concurrency issues? For example if myService.patch() is called twice simultaneously, and each .patch() is trying to update the same document, what happens?

**Comment by daffl** [comment]
It's using `model.update` (see https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/master/lib/service.js#L289). One reason the plugin is not working might be that you have to set `lean: false`.

The database adapter just makes plain database calls. I don't believe there is anything Feathers should do, handling concurrency would be more the job of the database.

**Comment by benedictkohtc** [comment]
Hmm I see, from what I've found, mongoose can sort of handle concurrency by incrementing and checking its `__v` values.

There appears to be a way to pass in mongoose options through feathers? `params.mongoose`? meaning to say I can do something like
```
.patch(
  someID,
  {
    myData: myValue
  },{
    $inc: { __v: 1 }
  })
```
I'm not too sure how to check whether the `__v` is as expected though.

Or perhaps would you consider checking for concurrency within the DB adapter itself?

**Comment by daffl** [comment]
You can do this in a hook by retrieving the old value first (e.g. adding it as `hook.original`) and then comparing it to the expected version. Further discussion in https://github.com/feathersjs-ecosystem/feathers-mongoose/issues always welcome but I am going to close this since it is not a Feathers core issue.
