### ISSUE TITLE
Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by marcus-sa** [feathersjs/feathers#815]
So I've created a few Adonis Providers for Feathers, and one of them is for feathers-sequelize.

I keep getting this error whenever I add hooks.

```bash
TypeError: Cannot read property 'bind' of undefined
[0]     at hooks.forEach.fn (C:\Users\esetm\Git\*******\node_modules\@feathersjs\commons\lib\hooks.js:166:21)
[0]     at Array.forEach (<anonymous>)
[0]     at Object.processHooks (C:\Users\esetm\Git\*******\node_modules\@feathersjs\commons\lib\hooks.js:164:9)
[0]     at Object.mixin.(anonymous function) (C:\Users\esetm\Git\*******\node_modules\@feathersjs\feathers\lib\hooks.js:57:27)
[0]     at Object.create (C:\Users\esetm\Git\*******\node_modules\uberproto\lib\proto.js:30:17)
[0]     at C:\Users\esetm\Git\*******\node_modules\@feathersjs\express\lib\rest\wrappers.js:60:26
[0]     at Layer.handle [as handle_request] (C:\Users\esetm\Git\*******\node_modules\express\lib\router\layer.js:95:5)
[0]     at next (C:\Users\esetm\Git\*******\node_modules\express\lib\router\route.js:137:13)
[0]     at next (C:\Users\esetm\Git\*******\node_modules\express\lib\router\route.js:131:14)
[0]     at next (C:\Users\esetm\Git\*******\node_modules\express\lib\router\route.js:131:14)
[0]     at Route.dispatch (C:\Users\esetm\Git\*******\node_modules\express\lib\router\route.js:112:3)
[0]     at Layer.handle [as handle_request] (C:\Users\esetm\Git\*******\node_modules\express\lib\router\layer.js:95:5)
[0]     at C:\Users\esetm\Git\*******\node_modules\express\lib\router\index.js:281:22
[0]     at Function.process_params (C:\Users\esetm\Git\*******\node_modules\express\lib\router\index.js:335:12)
[0]     at next (C:\Users\esetm\Git\*******\node_modules\express\lib\router\index.js:275:10)
[0]     at C:\Users\esetm\Git\*******\node_modules\@feathersjs\express\lib\rest\index.js:34:7
[0]     at Layer.handle [as handle_request] (C:\Users\esetm\Git\*******\node_modules\express\lib\router\layer.js:95:5)
[0]     at trim_prefix (C:\Users\esetm\Git\*******\node_modules\express\lib\router\index.js:317:13)
[0]     at C:\Users\esetm\Git\*******\node_modules\express\lib\router\index.js:284:7
[0]     at Function.process_params (C:\Users\esetm\Git\*******\node_modules\express\lib\router\index.js:335:12)
[0]     at next (C:\Users\esetm\Git\*******\node_modules\express\lib\router\index.js:275:10)
[0]     at C:\Users\esetm\Git\*******\node_modules\body-parser\lib\read.js:130:5
```

This is my model code:
```js
'use strict'

const auth = require('@feathersjs/authentication')
const local = require('@feathersjs/authentication-local')
const { restrictToOwner } = require('feathers-authentication-hooks')
const { discard } = require('feathers-hooks-common')

const { validateHook, unique, required, minLength, maxLength, match } = use('App/Validation')
const Model = use('Model')

module.exports = class Users extends Model {

  static get createSchema() {
    return {
      username: [required, minLength(6), maxLength(24)],
      password: [required, minLength(6), maxLength(255)],
      confirmPassword: [required, match('password')]
    }
  }

  static get serviceHooks() {
    return {
      before: {
        find: auth.hooks.authenticate('jwt'),
        get: auth.hooks.authenticate('jwt'),
        create: [validateHook(this.createSchema), discard('confirmPassword'), local.hooks.hashPassword()],
        update: [auth.hooks.authenticate('jwt'), restrictToOwner({ ownerField: 'id' })],
        patch: [auth.hooks.authenticate('jwt'), restrictToOwner({ ownerField: 'id' })],
      },
      after: {
        all: local.hooks.protect('password')
      }
    }
  }

  static get tableName() {
    return 'users'
  }

  static attributes({ STRING, INTEGER }) {
    return {
      username: {
        type: STRING,
        allowNull: false
      },
      password: {
        type: STRING,
        allowNull: false
      },
      rank: {
        type: INTEGER,
        defaultValue: 1
      }
    }
  }

}
```

and this is the provider code:

```js
'use strict'

const _ = require('lodash')
const BaseModel = require('./Model')
const pascalCase = require('pascal-case')
const Sequelize = require('sequelize')

module.exports = class FeathersSequelize {

    constructor(Rest, Ioc, Config, Helpers) {
        this._rest = Rest
        this._ioc = Ioc
        this._helpers = Helpers

        const config = Config.get('database')
        const dialect = config.connection
        const { connection } = config[dialect]

        this._modelsPath = 'App/Models'

        this.sequelize = new Sequelize(
            connection.database,
            connection.user,
            connection.password,
            {
                dialect,
                host: connection.host,
                pool: connection.pool,
                storage: connection.storage
            }
        )

        this._models = {}
        this._services = {}
    }

    _start() {
        const { models } = require(this._helpers.appRoot('start/app.js'))

        Object.keys(models).forEach(modelName => {
            const model = this._ioc.use(models[modelName])

            if (model.prototype instanceof BaseModel === false) {
              throw new Error(`${model.name} model must extend base model class`)
            }

            const options = _.mergeWith(model.options, {
              hooks: model.hooks instanceof Object
                ? model.hooks
                : {}
            })

            const sequelizeModel = this.sequelize.define(
                model.tableName,
                model.attributes(Sequelize),
                options
            )

            if (model.hooks instanceof Function) {
              model.hooks.bind(sequelizeModel)()
            }

            Object.getOwnPropertyNames(model).forEach(prop => {
              if (!sequelizeModel.hasOwnProperty(prop) && model[prop] instanceof Function) {
                  sequelizeModel[prop] = model[prop].bind(sequelizeModel)
              }
            })

            Object.getOwnPropertyNames(model.prototype).forEach(prop => {
                if (!sequelizeModel.prototype.hasOwnProperty(prop) && model.prototype[prop] instanceof Function) {
                    sequelizeModel.prototype[prop] = model.prototype[prop].bind(sequelizeModel.prototype)
                }
            })

            this._models[modelName] = sequelizeModel

            if (typeof model.createService === 'undefined' || model.createService || model.serviceName) {
              const service = require('feathers-sequelize')
              const serviceName = model.serviceName || model.tableName

              this._rest.app.use(serviceName, service({
                Model: sequelizeModel,
                events: model.events,
                id: model.id || 'id',
                raw: model.raw,
                paginate: model.paginate
              })).hooks(model.serviceHooks || {})

              this._ioc.singleton(`Services/${pascalCase(serviceName)}`, () => {
                return this._rest.app.service(serviceName)
              })
            }

            this._ioc.singleton(`Models/${modelName}`, (ioc) => sequelizeModel)
        })
    }

}
```

I've had nothing but problems with Feathers for the last few hours, and this is not the only errors that have occurred.

**Comment by daffl** [comment]
That error means that you are passing a hook that is not a function. From the code you posted, you probably want to have a look at `model.serviceHooks`.

**Comment by marcus-sa** [comment]
Sorry for my attitude yesterday. I really wanna thank you for this project, because it accomplish what I need.
I came to the solution that it was the `local.hooks.hashPassword()` hook that caused the error.
Removing it solved the issue.

**Comment by daffl** [comment]
The content type in the `Accept` header has to be `application/json` to get JSON.

If it is the built in hook, `local.hooks.hashPassword()` shouldn't return `undefined` or cause an error like that.

**Comment by marcus-sa** [comment]
I'm using Postman atm and setting the `Accept` header value to `application/json` doesn't change anything.
The error response gets generated using this script:

```js
const errors = require('@feathersjs/errors')

// ...

function validateHook(schema) {
  return async (hook) => {
    try {
      await createAsyncValidator(schema, { hook })(hook.data)
      return hook
    } catch (errorsValidation) {
      if (Object.keys(errorsValidation).length) {
        console.log(errorsValidation)
        throw new errors.BadRequest('Validation failed', errorsValidation)
      }
    }
  }
}
```

**Comment by daffl** [comment]
This looks like the standard Express error handler. For JSON formatted error the [express.errorHandler()](https://docs.feathersjs.com/api/express.html#expresserrorhandler) needs to be registered as the _last_ middleware in the middleware chain ([e.g. like in the feathers-chat](https://github.com/feathersjs/feathers-chat/blob/master/src/app.js#L49))

**Comment by marcus-sa** [comment]
I already chained the `express.errorHandler()` to be last, but due to my silly coding structure instead of adding middleware in the right chain order, it would just do it whenever the method got called.

Works fine now, thankfully.
