### ISSUE TITLE
how generate Foreign key with and see data JSON "sequelize"

### ISSUE THREAD

**Issue by HDCARDENAS2** [feathersjs/feathers#857]
hello, i have problem with associate methods of sequelize, I asked the team sequelize help, for solve this problem.

I would like to do this, but I do not know
```
{
    "total": 1,
    "limit": 1000,
    "skip": 0,
    "data": [
        {
            "core_function_id": "1",
            "description": "Ingresar solicitud",
            "core_url ": { "core_url_id": 1, "description": "data" },
            "json_logical": null,
            "json_update": null,
            "active": true,
            "created_at": "2018-04-09T20:01:34.491Z",
            "updated_at": "2018-04-09T20:01:34.491Z"
        }
    ]
}
```
service call soluction
```
    const app                   = this.options.app
    const core_url              = app.service('core-url').Model
    const core_function         = app.service('core-function').Model

    const coreUrl = await core_url.findOne({
      where: { core_url_id : 1 
      },
      include: [ core_function ]
    
    }).then(data => {
     
      console.log(JSON.stringify(data))

    })
```

this error show ,when associate two models

```
info: Feathers application started on http://localhost:3030
error:  SequelizeEagerLoadingError: core_function is not associated to core_url!
    at Function._getIncludedAssociation (/home/siut/siut_back_02/node_modules/sequelize/lib/model.js:582:13)
    at Function._validateIncludedElement (/home/siut/siut_back_02/node_modules/sequelize/lib/model.js:498:53)
    at options.include.options.include.map.include (/home/siut/siut_back_02/node_modules/sequelize/lib/model.js:394:37)
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (/home/siut/siut_back_02/node_modules/sequelize/lib/model.js:390:39)
    at Promise.try.then.then (/home/siut/siut_back_02/node_modules/sequelize/lib/model.js:1575:14)
    at tryCatcher (/home/siut/siut_back_02/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/siut/siut_back_02/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/siut/siut_back_02/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/siut/siut_back_02/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/siut/siut_back_02/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/siut/siut_back_02/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/siut/siut_back_02/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/siut/siut_back_02/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
```

my issue in sequelize

https://github.com/sequelize/sequelize/issues/9321
pls help

**Comment by daffl** [comment]
Since this problem seems to involve a more complex setup, the best way to get help is by providing a repository that easily allows to reproduce the issue.

**Comment by HDCARDENAS2** [comment]
These days I have tried to solve the problem, the previous problem solved by a declaring the model in the app and not in a service.

but i looked a one error, in the
model "models/core-url.model.js"
not implement this solution

```
  // eslint-disable-next-line no-unused-vars
  coreUrl.associate = function (models) {
    // Define associations here
    // See http://docs.sequelizejs.com/en/latest/docs/associations/
    coreUrl.hasOne(models.core_function, { foreignKey: 'core_url_id' })
    coreUrl.addScope('defaultScope', { include: [models.core_function]}, { override: true } )
   
  };
```

this generate this error

```
{
    "name": "GeneralError",
    "message": "Maximum call stack size exceeded",
    "code": 500,
    "className": "general-error",
    "data": {},
    "errors": {}
}
```
the correct code is in the child class,  "models/core-function.model.js"

```
  // eslint-disable-next-line no-unused-vars
  coreFunction.associate = function (models) {
    // Define associations here
    // See http://docs.sequelizejs.com/en/latest/docs/associations/
    coreFunction.belongsTo(models.core_url, { foreignKey: 'core_url_id' })
    coreFunction.addScope('defaultScope', {  include: [models.core_url] }, { override: true })
  }
```

ok.... in the service "http://localhost:3031/core-function/"
i see this.

```
{
    "total": 1,
    "limit": 10,
    "skip": 0,
    "data": [
        {
            "core_function_id": "1",
            "description": "Ingresar solicitud",
            "core_url_id": "1",
            "created_at": "2018-04-27T05:19:28.908Z",
            "updated_at": "2018-04-27T05:19:28.908Z",
            "core_url.core_url_id": "1",
            "core_url.description": "solicitud.html",
            "core_url.created_at": "2018-04-27T05:19:22.517Z",
            "core_url.updated_at": "2018-04-27T05:19:22.517Z"
        }
    ]
}
```

but I need to return it like this

```
{
    "total": 1,
    "limit": 1000,
    "skip": 0,
    "data": [
        {
            "core_function_id": "1",
            "description": "Ingresar solicitud",
            "core_url ": { "core_url_id": 1, "description": "data" },
            "active": true,
            "created_at": "2018-04-09T20:01:34.491Z",
            "updated_at": "2018-04-09T20:01:34.491Z"
        }
    ]
}
```

then i created a custom service "services/custom-find /custom-find.class.js"
with the recommendation of sequelize team

```
  async find (params) {

    const app                   = this.options.app
    const core_url              = app.service('core-url').Model
    const core_function         = app.service('core-function').Model

   await core_function.findOne({
      where: { core_function_id : 1 
      },
      include: [ core_url ]
    
    }).then(data => {
     
      console.log(JSON.stringify(data))

    })

    return [];
  }
```
"http://localhost:3031/core-function/"
and now print this errror
```
{
    "name": "GeneralError",
    "message": "table name \"core_url\" specified more than once",
    "code": 500,
    "className": "general-error",
    "data": {},
    "errors": {}
}
```

GIT repository
https://github.com/HDCARDENAS2/feathers_squelize_foreign_k

DB in /db/script.sql

thanks for help

**Comment by daffl** [comment]
This looks like a Sequelize issue to me. In your `core_function` model you aded `coreFunction.addScope('defaultScope', {  include: [models.core_url] }, { override: true })` and in the custom service you are again including it with `include: [ core_url ]`.

**Comment by daffl** [comment]
I don't know if I am following the problem. Have you tried removing `include: [ core_url ]` from `custom-find.class.js`? It should already be included through the `defaultScope` (this is also what the error is complaining about).

**Comment by HDCARDENAS2** [comment]
Mmmm

**Comment by HDCARDENAS2** [comment]
that part of the error I already understood, now the question is how to return the core_url []
```
{
    "total": 1,
    "limit": 1000,
    "skip": 0,
    "data": [
        {
            "core_function_id": "1",
            "description": "Ingresar solicitud",
            "core_url ": { "core_url_id": 1, "description": "data" },
            "json_logical": null,
            "json_update": null,
            "active": true,
            "created_at": "2018-04-09T20:01:34.491Z",
            "updated_at": "2018-04-09T20:01:34.491Z"
        }
    ]
}
```
there is a method for not return this, and return in [ ]
```

{
    "total": 1,
    "limit": 10,
    "skip": 0,
    "data": [
        {
            "core_function_id": "1",
            "description": "Ingresar solicitud",
            "core_url_id": "1",
            "created_at": "2018-04-27T05:19:28.908Z",
            "updated_at": "2018-04-27T05:19:28.908Z",
            "core_url.core_url_id": "1",
            "core_url.description": "solicitud.html",
            "core_url.created_at": "2018-04-27T05:19:22.517Z",
            "core_url.updated_at": "2018-04-27T05:19:22.517Z"
        }
    ]
}
``` 

How make to return entity in array

**Comment by daffl** [comment]
You have to set the `raw` [feathers-sequelize service option](https://github.com/feathersjs-ecosystem/feathers-sequelize#serviceoptions) to `raw: false` (e.g. by adding it [here](https://github.com/HDCARDENAS2/feathers_squelize_foreign_k/blob/master/src/services/core-function/core-function.service.js#L10)).
