### ISSUE TITLE
Error: 'all' is not a valid hook type

### ISSUE THREAD

**Issue by Shadowman4205** [feathersjs/feathers#899]
Hello,
is this type removed? I am getting this error after updating to last version.

```
Error: 'all' is not a valid hook type
    at each (C:\TempProjects\proj\node_modules\@feathersjs\commons\lib\hooks.js:205:17)
    at Object.keys.forEach.key (C:\TempProjects\proj\node_modules\@feathersjs\commons\lib\utils.js:12:39)
    at Array.forEach (<anonymous>)
    at each (C:\TempProjects\proj\node_modules\@feathersjs\commons\lib\utils.js:12:24)
    at Object.hooks (C:\TempProjects\proj\node_modules\@feathersjs\commons\lib\hooks.js:203:7)
    ....
```

**Comment by Shadowman4205** [comment]
Sorry but implementation
