### ISSUE TITLE
FeatherJs Errors without even writing a single line of code

### ISSUE THREAD

**Issue by lajap** [feathersjs/feathers#909]
### FeatherJs Errors without even writing a single line of code

I just got started with feathersjs and I'm already disappointed. Probably it's only me, but I get errors after generating authentication.
`feathers g authentication `

I tried to post this `{"email": "feathers@madman.com","password": "vell"}` after succesfully posting `{"email": "feath@madman.com","password": "bell"}` to `http://localhost:3030/users/` in **Postman**, using **NEDB**. I get this: 
```
{
    "name": "GeneralError",
    "message": "Can't insert key undefined, it violates the unique constraint",
    "code": 500,
    "className": "general-error",
    "data": {},
    "errors": {}
}
```

###Error logs:
```
error: Error: Can't insert key undefined, it violates the unique constraint
    at _AVLTree.insert (C:\Users\Deo\Documents\Projects\Node Js\feathersjs\feather chat\backend\node_modules\binary-search-tree\lib\avltree.js:273:19)
    at AVLTree.insert (C:\Users\Deo\Documents\Projects\Node Js\feathersjs\feather chat\backend\node_modules\binary-search-tree\lib\avltree.js:307:27)
    at Index.insert (C:\Users\Deo\Documents\Projects\Node Js\feathersjs\feather chat\backend\node_modules\nedb\lib\indexes.js:77:15)
    at Datastore.addToIndexes (C:\Users\Deo\Documents\Projects\Node Js\feathersjs\feather chat\backend\node_modules\nedb\lib\datastore.js:180:29)
    at Datastore._insertInCache (C:\Users\Deo\Documents\Projects\Node Js\feathersjs\feather chat\backend\node_modules\nedb\lib\datastore.js:402:10)
    at Datastore._insert (C:\Users\Deo\Documents\Projects\Node Js\feathersjs\feather chat\backend\node_modules\nedb\lib\datastore.js:348:10)
    at C:\Users\Deo\Documents\Projects\Node Js\feathersjs\feather chat\backend\node_modules\nedb\lib\executor.js:40:13
    at Immediate.process [as _onImmediate] (C:\Users\Deo\Documents\Projects\Node Js\feathersjs\feather chat\backend\node_modules\nedb\node_modules\async\lib\async.js:731:21)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
```

**Comment by daffl** [comment]
That means an entry with that `email` is already in your database. If you remove the `data` folder it will work but it can only be added once.

**Comment by lajap** [comment]
Ok, thanks. Great work by the way.
