### ISSUE TITLE
Should socket calls require a callback?

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers#96]
This feels like a bug to me.  I've been trying to do a one-off update to the server like this:

```js
socket.emit("api/preferences::update", pref._id, pref, {});
```

Which results in a server crash on this error:

```
/Users/marshallthompson//Sites/MMA/node_modules/feathers/node_modules/rubberduck/lib/rubberduck.js:67
        throw e;
              ^
TypeError: Property 'callback' of object #<Object> is not a function
    at hookCallback (/Users/marshallthompson//Sites/MMA/node_modules/feathers-hooks/lib/before.js:39:35)
    at Object.exports.requireAuth (/Users/marshallthompson//Sites/MMA/server/hook-library.js:30:12)
    at Object.fn (/Users/marshallthompson//Sites/MMA/node_modules/feathers-hooks/lib/before.js:49:32)
    at Object.self.(anonymous function) (/Users/marshallthompson//Sites/MMA/node_modules/feathers/node_modules/uberproto/lib/proto.js:61:21)
    at hookCallback (/Users/marshallthompson//Sites/MMA/node_modules/feathers-hooks/lib/before.js:44:22)
    at Object.exports.setUserID (/Users/marshallthompson//Sites/MMA/server/hook-library.js:120:10)
    at Object.fn (/Users/marshallthompson//Sites/MMA/node_modules/feathers-hooks/lib/before.js:49:32)
    at Object.self.(anonymous function) (/Users/marshallthompson//Sites/MMA/node_modules/feathers/node_modules/uberproto/lib/proto.js:61:21)
    at Object.wrapped [as update] (/Users/marshallthompson//Sites/MMA/node_modules/feathers/node_modules/rubberduck/lib/rubberduck.js:63:12)
    at Socket.<anonymous> (/Users/marshallthompson//Sites/MMA/node_modules/feathers/lib/providers/socket/commons.js:28:23)
```

If I put the callback in place like this:

```js 
socket.emit('api/preferences::update', pref._id, pref, {}, function(error, data) {
	console.log(data);
});
```

It works as expected.  That doesn't seem right to me.  Do socket calls always require the callback in place?

**Comment by marshallswain** [comment]
This is fixed in #102.
