### ISSUE TITLE
Verifier implementation

### ISSUE THREAD

**Issue by guillaumervls** [feathersjs/feathers#978]
Hi and thanks for the framework,

I need to customize my `local` authentication strategy. For that I can provide a subclass of `local.Verifier` with a custom `verify` method. The problem is that in this method I need to return the token payload, and if I don't use the form ``{ [`${this.options.entity}Id`]: id }`` like [in the default one](https://github.com/feathersjs/feathers/blob/1cc39eeea2e2084d9e6cd692c4aef446c1a235c4/packages/authentication-jwt/lib/verifier.js#L30), it won't be working with the `jwt.Verifier` class used by the `jwt` strategy (among other since it looks like each strategy module gets its own `Verifier` class).

Should there be a single source of truth for this ? Like somewhere a unique (possibly also overridable) function `entity => jwtPayload` ?

Am I missing something ?

Cheers

**Comment by daffl** [comment]
Yes there should be and the use id should really be included in the tokens `sub` header instead of the payload. This will be possible [in the next version](https://blog.feathersjs.com/in-the-crows-nest-feathersjs-roadmap-update-41a1eafc6f5).

**Comment by matiaslopezd** [comment]
@daffl Hi!

I have a problems follow [this docs](https://docs.feathersjs.com/api/authentication/local.html#verifier) trying create my custom `Verifier` because import return error of syntax.

```javascript
import local, { Verifier } from '@feathersjs/authentication-local';

class CustomVerifier extends Verifier {
 //Custom code
}
```

```console
import local, { Verifier } from '@feathersjs/authentication-local';
       ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\xampp\htdocs\api-feathers\src\app.js:22:24)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

The only way to make my custom `Verifier` is with this method:

`authentication.js`
```javascript
const local = require('@feathersjs/authentication-local');

class CustomVerifier extends local.Verifier {
 //Custom code
}
```

**Comment by daffl** [comment]
It is indeed, I updated the docs.

**Comment by matiaslopezd** [comment]
The same with [JWT Verifier](https://docs.feathersjs.com/api/authentication/jwt.html#customizing-the-verifier). Pull request: [#1276](https://github.com/feathersjs/docs/pull/1276) in docs.

**Comment by daffl** [comment]
Setting the `sub` properly has been implemented in Feathers v4 authentication. See the [Migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information on how to upgrade.
